# Generated by Django 5.0.3 on 2024-04-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entradap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64, verbose_name='Nombre:')),
                ('apellido', models.CharField(default='', max_length=64, verbose_name='Apellido:')),
                ('cedula', models.CharField(default='', max_length=64, verbose_name='Cédula:')),
                ('telefono', models.CharField(default='', max_length=64, verbose_name='Teléfono:')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('direccion', models.CharField(default='', max_length=64, verbose_name='Dirección:')),
                ('cargo', models.CharField(default='', max_length=64, verbose_name='Cargo:')),
                ('hora', models.CharField(default='', max_length=64, verbose_name='Hora de Entrada:')),
            ],
        ),
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64, verbose_name='Nombre:')),
                ('apellido', models.CharField(default='', max_length=64, verbose_name='Apellido:')),
                ('cedula', models.CharField(default='', max_length=64, verbose_name='Cédula:')),
                ('tipo', models.CharField(default='', max_length=64, verbose_name='Tipo de Incidente:')),
                ('descripcion', models.CharField(default='', max_length=64, verbose_name='Descripción:')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('direccion', models.CharField(default='', max_length=64, verbose_name='Dirección:')),
                ('cargo', models.CharField(default='', max_length=64, verbose_name='Cargo:')),
                ('hora', models.CharField(default='', max_length=64, verbose_name='Hora de Entrada:')),
            ],
        ),
        migrations.CreateModel(
            name='Salidap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64, verbose_name='Nombre:')),
                ('apellido', models.CharField(default='', max_length=64, verbose_name='Apellido:')),
                ('cedula', models.CharField(default='', max_length=64, verbose_name='Cédula:')),
                ('telefono', models.CharField(default='', max_length=64, verbose_name='Teléfono:')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('direccion', models.CharField(default='', max_length=64, verbose_name='Dirección:')),
                ('cargo', models.CharField(default='', max_length=64, verbose_name='Cargo:')),
                ('hora', models.CharField(default='', max_length=64, verbose_name='Hora de Entrada:')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=64, verbose_name='Nombre:')),
                ('apellido', models.CharField(default='', max_length=64, verbose_name='Apellido:')),
                ('cedula', models.CharField(default='', max_length=64, verbose_name='Cédula:')),
                ('tipo', models.CharField(default='', max_length=64, verbose_name='Tipo:')),
                ('transporte', models.CharField(default='', max_length=64, verbose_name='Transporte:')),
                ('modelo', models.CharField(default='', max_length=64, verbose_name='Modelo:')),
                ('placa', models.CharField(default='', max_length=64, verbose_name='Placa:')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.CharField(default='', max_length=64, verbose_name='Hora:')),
            ],
        ),
    ]
