# Generated by Django 5.0.3 on 2024-04-03 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehiculos',
        ),
    ]
