# Generated by Django 5.0.3 on 2024-04-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_delete_vehiculos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=64, verbose_name='Nombre:')),
                ('apellido', models.CharField(default='', max_length=64, verbose_name='Apellido:')),
                ('cedula', models.CharField(default='', max_length=64, verbose_name='Cédula:')),
                ('transporte', models.CharField(default='', max_length=64, verbose_name='Transporte:')),
                ('modelo', models.CharField(default='', max_length=64, verbose_name='Modelo:')),
                ('capagasolina', models.CharField(default='', max_length=64, verbose_name='Capacidad de Gasolina:')),
                ('entratgasolina', models.CharField(default='', max_length=64, verbose_name='Gasolina entrante:')),
                ('salientgasolina', models.CharField(default='', max_length=64, verbose_name='Gasolina saliente:')),
                ('placa', models.CharField(default='', max_length=64, verbose_name='Placa:')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.CharField(default='', max_length=64, verbose_name='Hora:')),
            ],
        ),
        migrations.CreateModel(
            name='Patrulla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=64, verbose_name='Nombre:')),
                ('apellido', models.CharField(default='', max_length=64, verbose_name='Apellido:')),
                ('cedula', models.CharField(default='', max_length=64, verbose_name='Cédula:')),
                ('transporte', models.CharField(default='', max_length=64, verbose_name='Transporte:')),
                ('modelo', models.CharField(default='', max_length=64, verbose_name='Modelo:')),
                ('capagasolina', models.CharField(default='', max_length=64, verbose_name='Capacidad de Gasolina:')),
                ('entratgasolina', models.CharField(default='', max_length=64, verbose_name='Gasolina entrante:')),
                ('salientgasolina', models.CharField(default='', max_length=64, verbose_name='Gasolina saliente:')),
                ('placa', models.CharField(default='', max_length=64, verbose_name='Placa:')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.CharField(default='', max_length=64, verbose_name='Hora:')),
            ],
        ),
    ]
