# Generated by Django 5.1.1 on 2025-04-20 21:44

import django.core.validators
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=6, verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_by', models.CharField(max_length=6, verbose_name='Actualizado por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_by', models.CharField(blank=True, max_length=6, null=True, verbose_name='Eliminado por')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('fechai', models.DateField(verbose_name='Fecha de Inicio')),
                ('fechaf', models.DateField(verbose_name='Fecha Final')),
                ('objetiv', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(255), helpers.validForm.TextValidator()], verbose_name='Objetivos:')),
                ('meta', models.CharField(default='', max_length=64, verbose_name='Meta:')),
            ],
            options={
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
                'permissions': [('listar_actividad', 'Puede listar actividades'), ('agregar_actividad', 'Puede agregar actividad'), ('ver_actividad', 'Puede ver actividad'), ('editar_actividad', 'Puede actualizar actividad'), ('eliminar_actividad', 'Puede eliminar actividad')],
            },
        ),
        migrations.CreateModel(
            name='Infraestructura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=6, verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_by', models.CharField(max_length=6, verbose_name='Actualizado por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_by', models.CharField(blank=True, max_length=6, null=True, verbose_name='Eliminado por')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('estado', models.CharField(choices=[('1', 'Amazonas'), ('2', 'Anzoátegui'), ('3', 'Apure'), ('4', 'Aragua'), ('5', 'Barinas'), ('6', 'Bolívar'), ('7', 'Carabobo'), ('8', 'Cojedes'), ('9', 'Delta Amacuro'), ('10', 'Falcón'), ('11', 'Guárico'), ('12', 'Lara'), ('13', 'Mérida'), ('14', 'Miranda'), ('15', 'Monagas'), ('16', 'Nueva Esparta'), ('17', 'Portuguesa'), ('18', 'Sucre'), ('19', 'Táchira'), ('20', 'Trujillo'), ('21', 'Vargas'), ('22', 'Yaracuy'), ('23', 'Zulia'), ('24', 'Distrito Capital')], max_length=2, verbose_name='Estado de la infraestructura')),
                ('mes', models.CharField(choices=[('ene', 'Enero'), ('feb', 'Febrero'), ('mar', 'Marzo'), ('abr', 'Abril'), ('may', 'Mayo'), ('jun', 'Junio'), ('jul', 'Julio'), ('ago', 'Agosto'), ('sep', 'Septiembre'), ('oct', 'Octubre'), ('nov', 'Noviembre'), ('dic', 'Diciembre')], max_length=3, verbose_name='Mes programado')),
                ('infraestructura', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Nombre de la infraestructura')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000), helpers.validForm.PositiveIntegerValidator()], verbose_name='Cantidad estimada')),
            ],
            options={
                'verbose_name': 'infraestructura',
                'verbose_name_plural': 'infraestructuras',
                'permissions': [('listar_infraestructura', 'Puede listar infraestructura'), ('agregar_infraestructura', 'Puede agregar infraestructura'), ('ver_infraestructura', 'Puede ver infraestructura'), ('editar_infraestructura', 'Puede actualizar infraestructura'), ('eliminar_infraestructura', 'Puede eliminar infraestructura')],
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=6, verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_by', models.CharField(max_length=6, verbose_name='Actualizado por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_by', models.CharField(blank=True, max_length=6, null=True, verbose_name='Eliminado por')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('fechai', models.DateField(verbose_name='Fecha de Inicio')),
                ('fechaf', models.DateField(verbose_name='Fecha Final')),
                ('objetiv', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Objetivos:')),
                ('meta', models.CharField(default='', max_length=64, verbose_name='Meta:')),
            ],
            options={
                'verbose_name': 'objetivo',
                'verbose_name_plural': 'objetivos',
                'permissions': [('listar_objetivo', 'Puede listar objetivos'), ('agregar_objetivo', 'Puede agregar objetivo'), ('ver_objetivo', 'Puede ver objetivo'), ('editar_objetivo', 'Puede actualizar objetivo'), ('eliminar_objetivo', 'Puede eliminar objetivo')],
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=6, verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_by', models.CharField(max_length=6, verbose_name='Actualizado por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_by', models.CharField(blank=True, max_length=6, null=True, verbose_name='Eliminado por')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('estado', models.CharField(choices=[('1', 'Amazonas'), ('2', 'Anzoátegui'), ('3', 'Apure'), ('4', 'Aragua'), ('5', 'Barinas'), ('6', 'Bolívar'), ('7', 'Carabobo'), ('8', 'Cojedes'), ('9', 'Delta Amacuro'), ('10', 'Falcón'), ('11', 'Guárico'), ('12', 'Lara'), ('13', 'Mérida'), ('14', 'Miranda'), ('15', 'Monagas'), ('16', 'Nueva Esparta'), ('17', 'Portuguesa'), ('18', 'Sucre'), ('19', 'Táchira'), ('20', 'Trujillo'), ('21', 'Vargas'), ('22', 'Yaracuy'), ('23', 'Zulia'), ('24', 'Distrito Capital')], max_length=2, verbose_name='Estado del transporte')),
                ('mes', models.CharField(choices=[('ene', 'Enero'), ('feb', 'Febrero'), ('mar', 'Marzo'), ('abr', 'Abril'), ('may', 'Mayo'), ('jun', 'Junio'), ('jul', 'Julio'), ('ago', 'Agosto'), ('sep', 'Septiembre'), ('oct', 'Octubre'), ('nov', 'Noviembre'), ('dic', 'Diciembre')], max_length=3, verbose_name='Mes de operación')),
                ('transporte', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Tipo de transporte')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000), helpers.validForm.PositiveIntegerValidator()], verbose_name='Cantidad de unidades')),
            ],
            options={
                'verbose_name': 'transporte',
                'verbose_name_plural': 'transportes',
                'permissions': [('listar_transporte', 'Puede listar transporte'), ('agregar_transporte', 'Puede agregar transporte'), ('ver_transporte', 'Puede ver transporte'), ('editar_transporte', 'Puede actualizar transporte'), ('eliminar_transporte', 'Puede eliminar transporte')],
            },
        ),
    ]
