# Generated by Django 5.1.1 on 2025-03-22 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'permissions': [('listar_actividad', 'Puede listar actividades'), ('agregar_actividad', 'Puede agregar actividad'), ('ver_actividad', 'Puede ver actividad'), ('editar_actividad', 'Puede actualizar actividad'), ('eliminar_actividad', 'Puede eliminar actividad')], 'verbose_name': 'actividad', 'verbose_name_plural': 'actividades'},
        ),
        migrations.AlterModelOptions(
            name='infraestructura',
            options={'permissions': [('listar_infraestructura', 'Puede listar infraestructura'), ('agregar_infraestructura', 'Puede agregar infraestructura'), ('ver_infraestructura', 'Puede ver infraestructura'), ('editar_infraestructura', 'Puede actualizar infraestructura'), ('eliminar_infraestructura', 'Puede eliminar infraestructura')], 'verbose_name': 'infraestructura', 'verbose_name_plural': 'infraestructuras'},
        ),
        migrations.AlterModelOptions(
            name='llamada',
            options={'permissions': [('listar_llamada', 'Puede listar llamada'), ('agregar_llamada', 'Puede agregar llamada'), ('ver_llamada', 'Puede ver llamada'), ('editar_llamada', 'Puede actualizar llamada'), ('eliminar_llamada', 'Puede eliminar llamada')], 'verbose_name': 'llamada', 'verbose_name_plural': 'llamadas'},
        ),
        migrations.AlterModelOptions(
            name='objetivo',
            options={'permissions': [('listar_objetivo', 'Puede listar objetivos'), ('agregar_objetivo', 'Puede agregar objetivo'), ('ver_objetivo', 'Puede ver objetivo'), ('editar_objetivo', 'Puede actualizar objetivo'), ('eliminar_objetivo', 'Puede eliminar objetivo')], 'verbose_name': 'objetivo', 'verbose_name_plural': 'objetivos'},
        ),
        migrations.AlterModelOptions(
            name='transporte',
            options={'permissions': [('listar_transporte', 'Puede listar transporte'), ('agregar_transporte', 'Puede agregar transporte'), ('ver_transporte', 'Puede ver transporte'), ('editar_transporte', 'Puede actualizar transporte'), ('eliminar_transporte', 'Puede eliminar transporte')], 'verbose_name': 'transporte', 'verbose_name_plural': 'transportes'},
        ),
    ]
