# Generated by Django 5.1.1 on 2025-04-17 20:49

import django.core.validators
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llamada',
            name='falsa',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), helpers.validForm.PositiveIntegerValidator()], verbose_name='Llamadas falsas'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='informativa',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), helpers.validForm.PositiveIntegerValidator()], verbose_name='Llamadas informativas'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='realesf',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), helpers.validForm.PositiveIntegerValidator()], verbose_name='Llamadas reales finalizadas'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='realesno',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), helpers.validForm.PositiveIntegerValidator()], verbose_name='Llamadas reales no atendidas'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='videop',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), helpers.validForm.PositiveIntegerValidator()], verbose_name='Videollamadas protección'),
        ),
    ]
