# Generated by Django 5.1.1 on 2025-04-18 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0002_alter_llamada_falsa_alter_llamada_informativa_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Llamada',
        ),
    ]
