# Generated by Django 5.1.1 on 2025-03-29 18:44

import django.core.validators
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0002_alter_actividad_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='objetiv',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(255), helpers.validForm.TextValidator()], verbose_name='Objetivos:'),
        ),
        migrations.AlterField(
            model_name='infraestructura',
            name='cantidad',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxLengthValidator(64), helpers.validForm.PositiveIntegerValidator()], verbose_name='Cantidad estimada'),
        ),
        migrations.AlterField(
            model_name='infraestructura',
            name='estado',
            field=models.CharField(choices=[('1', 'Amazonas'), ('2', 'Anzoátegui'), ('3', 'Apure'), ('4', 'Aragua'), ('5', 'Barinas'), ('6', 'Bolívar'), ('7', 'Carabobo'), ('8', 'Cojedes'), ('9', 'Delta Amacuro'), ('10', 'Falcón'), ('11', 'Guárico'), ('12', 'Lara'), ('13', 'Mérida'), ('14', 'Miranda'), ('15', 'Monagas'), ('16', 'Nueva Esparta'), ('17', 'Portuguesa'), ('18', 'Sucre'), ('19', 'Táchira'), ('20', 'Trujillo'), ('21', 'Vargas'), ('22', 'Yaracuy'), ('23', 'Zulia'), ('24', 'Distrito Capital')], max_length=2, verbose_name='Estado de la infraestructura'),
        ),
        migrations.AlterField(
            model_name='infraestructura',
            name='infraestructura',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Nombre de la infraestructura'),
        ),
        migrations.AlterField(
            model_name='infraestructura',
            name='mes',
            field=models.CharField(choices=[('ene', 'Enero'), ('feb', 'Febrero'), ('mar', 'Marzo'), ('abr', 'Abril'), ('may', 'Mayo'), ('jun', 'Junio'), ('jul', 'Julio'), ('ago', 'Agosto'), ('sep', 'Septiembre'), ('oct', 'Octubre'), ('nov', 'Noviembre'), ('dic', 'Diciembre')], max_length=3, verbose_name='Mes programado'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='falsa',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinValueValidator(1), helpers.validForm.PositiveIntegerValidator()], verbose_name='Llamadas falsas'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='informativa',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinValueValidator(1), helpers.validForm.PositiveIntegerValidator()], verbose_name='Llamadas informativas'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='mes',
            field=models.CharField(choices=[('ene', 'Enero'), ('feb', 'Febrero'), ('mar', 'Marzo'), ('abr', 'Abril'), ('may', 'Mayo'), ('jun', 'Junio'), ('jul', 'Julio'), ('ago', 'Agosto'), ('sep', 'Septiembre'), ('oct', 'Octubre'), ('nov', 'Noviembre'), ('dic', 'Diciembre')], max_length=3, verbose_name='Mes:'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='realesf',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinValueValidator(1), helpers.validForm.PositiveIntegerValidator()], verbose_name='Llamadas reales finalizadas'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='realesno',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinValueValidator(1), helpers.validForm.PositiveIntegerValidator()], verbose_name='Llamadas reales no atendidas'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='videop',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinValueValidator(1), helpers.validForm.PositiveIntegerValidator()], verbose_name='Videollamadas protección'),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='objetiv',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Objetivos:'),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='cantidad',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxLengthValidator(64), helpers.validForm.PositiveIntegerValidator()], verbose_name='Cantidad de unidades'),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='estado',
            field=models.CharField(choices=[('1', 'Amazonas'), ('2', 'Anzoátegui'), ('3', 'Apure'), ('4', 'Aragua'), ('5', 'Barinas'), ('6', 'Bolívar'), ('7', 'Carabobo'), ('8', 'Cojedes'), ('9', 'Delta Amacuro'), ('10', 'Falcón'), ('11', 'Guárico'), ('12', 'Lara'), ('13', 'Mérida'), ('14', 'Miranda'), ('15', 'Monagas'), ('16', 'Nueva Esparta'), ('17', 'Portuguesa'), ('18', 'Sucre'), ('19', 'Táchira'), ('20', 'Trujillo'), ('21', 'Vargas'), ('22', 'Yaracuy'), ('23', 'Zulia'), ('24', 'Distrito Capital')], max_length=2, verbose_name='Estado del transporte'),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='mes',
            field=models.CharField(choices=[('ene', 'Enero'), ('feb', 'Febrero'), ('mar', 'Marzo'), ('abr', 'Abril'), ('may', 'Mayo'), ('jun', 'Junio'), ('jul', 'Julio'), ('ago', 'Agosto'), ('sep', 'Septiembre'), ('oct', 'Octubre'), ('nov', 'Noviembre'), ('dic', 'Diciembre')], max_length=3, verbose_name='Mes de operación'),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='transporte',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Tipo de transporte'),
        ),
    ]
