# Generated by Django 5.1.1 on 2025-04-06 23:22

import django.core.validators
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0002_alter_infraestructura_cantidad_alter_llamada_falsa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraestructura',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000), helpers.validForm.PositiveIntegerValidator()], verbose_name='Cantidad estimada'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='falsa',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), helpers.validForm.PositiveIntegerValidator()], verbose_name='Llamadas falsas'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='informativa',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), helpers.validForm.PositiveIntegerValidator()], verbose_name='Llamadas informativas'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='realesf',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), helpers.validForm.PositiveIntegerValidator()], verbose_name='Llamadas reales finalizadas'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='realesno',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), helpers.validForm.PositiveIntegerValidator()], verbose_name='Llamadas reales no atendidas'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='videop',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), helpers.validForm.PositiveIntegerValidator()], verbose_name='Videollamadas protección'),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000), helpers.validForm.PositiveIntegerValidator()], verbose_name='Cantidad de unidades'),
        ),
    ]
