# Generated by Django 5.1.1 on 2025-03-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidencia',
            options={'permissions': [('listar_incidencia', 'Puede listar incidencia'), ('agregar_incidencia', 'Puede agregar incidencia'), ('ver_incidencia', 'Puede ver incidencia'), ('editar_incidencia', 'Puede actualizar incidencia'), ('eliminar_incidencia', 'Puede eliminar incidencia')], 'verbose_name': 'Incidencia', 'verbose_name_plural': 'Incidencias'},
        ),
        migrations.AlterModelOptions(
            name='uri',
            options={'permissions': [('listar_uri', 'Puede listar uri'), ('agregar_uri', 'Puede agregar uri'), ('ver_uri', 'Puede ver uri'), ('editar_uri', 'Puede actualizar uri'), ('eliminar_uri', 'Puede eliminar uri')], 'verbose_name': 'Unidad de repuesta inmediata', 'verbose_name_plural': 'Unidades de repuestas inmediatas'},
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='tipo_solicitud',
            field=models.CharField(choices=[('soliint', 'Solicitud Interna'), ('soliext', 'Solicitud Externa')], max_length=10, verbose_name='Tipo de Solicitud'),
        ),
    ]
