# Generated by Django 5.1.1 on 2025-04-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(choices=[('Dtto. Capital', 'Distrito Capital'), ('Amazonas', 'Amazonas'), ('Anzoátegui', 'Anzoátegui'), ('Apure', 'Apure'), ('Aragua', 'Aragua'), ('Barinas', 'Barinas'), ('Bolívar', 'Bolívar'), ('Carabobo', 'Carabobo'), ('Cojedes', 'Cojedes'), ('Delta Amacuro', 'Delta Amacuro'), ('Falcón', 'Falcón'), ('Guárico', 'Guárico'), ('Lara', 'Lara'), ('Mérida', 'Mérida'), ('Miranda', 'Miranda'), ('Monagas', 'Monagas'), ('Nva. Esparta', 'Nueva Esparta'), ('Portuguesa', 'Portuguesa'), ('Sucre', 'Sucre'), ('Táchira', 'Táchira'), ('Trujillo', 'Trujillo'), ('Vargas', 'Vargas'), ('Yaracuy', 'Yaracuy'), ('Zulia', 'Zulia')], max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='uri',
            name='estado_evento',
            field=models.CharField(blank=True, choices=[('Dtto. Capital', 'Distrito Capital'), ('Amazonas', 'Amazonas'), ('Anzoátegui', 'Anzoátegui'), ('Apure', 'Apure'), ('Aragua', 'Aragua'), ('Barinas', 'Barinas'), ('Bolívar', 'Bolívar'), ('Carabobo', 'Carabobo'), ('Cojedes', 'Cojedes'), ('Delta Amacuro', 'Delta Amacuro'), ('Falcón', 'Falcón'), ('Guárico', 'Guárico'), ('Lara', 'Lara'), ('Mérida', 'Mérida'), ('Miranda', 'Miranda'), ('Monagas', 'Monagas'), ('Nva. Esparta', 'Nueva Esparta'), ('Portuguesa', 'Portuguesa'), ('Sucre', 'Sucre'), ('Táchira', 'Táchira'), ('Trujillo', 'Trujillo'), ('Vargas', 'Vargas'), ('Yaracuy', 'Yaracuy'), ('Zulia', 'Zulia')], max_length=15, null=True, verbose_name='Estado del Evento'),
        ),
        migrations.AlterField(
            model_name='uri',
            name='genero_acompanante',
            field=models.CharField(blank=True, choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], max_length=9, null=True, verbose_name='Genero del acompañante'),
        ),
        migrations.AlterField(
            model_name='uri',
            name='generopaciente',
            field=models.CharField(blank=True, choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], max_length=9, null=True, verbose_name='Genero del Paciente'),
        ),
    ]
