# Generated by Django 5.1.1 on 2025-04-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uri',
            name='centroAsistencial',
        ),
        migrations.RemoveField(
            model_name='uri',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='uri',
            name='eje_evento',
        ),
        migrations.AddField(
            model_name='uri',
            name='ambulatorio',
            field=models.CharField(blank=True, help_text='Datos del Centro Asistencial donde fue recibido el paciente', max_length=30, null=True, verbose_name='Ambulatorio/Hospital/Clínica'),
        ),
        migrations.AddField(
            model_name='uri',
            name='apellido_acompanante',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido del Acompañante'),
        ),
        migrations.AddField(
            model_name='uri',
            name='apellido_testigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido del Testigo'),
        ),
        migrations.AddField(
            model_name='uri',
            name='apellidopaciente',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellidos del Paciente'),
        ),
        migrations.AddField(
            model_name='uri',
            name='contactonopaciente',
            field=models.CharField(blank=True, choices=[('sinlesion', 'No habia lesionados'), ('pacientras', 'Paciente trasladado antes de llegar la unidad')], max_length=50, null=True, verbose_name='Descripción del Servicio donde no hubo contacto con el paciente'),
        ),
        migrations.AddField(
            model_name='uri',
            name='contactopaciente',
            field=models.CharField(blank=True, choices=[('paciensig', 'Paciente ingresa con signos vitales'), ('atendtra', 'Atendido en el sitio sin traslado'), ('pacienfal', 'Paciente fallece durante el traslado'), ('paciensin', 'Paciente fallece antes de llegar la unidad')], max_length=50, null=True, verbose_name='Descripción del Servicio donde hubo contacto con el paciente'),
        ),
        migrations.AlterField(
            model_name='uri',
            name='accidenteVehicular',
            field=models.CharField(blank=True, choices=[('noapli', 'No aplica'), ('colisi', 'Colisión'), ('choque', 'Choque'), ('volca', 'Volcamiento'), ('arrolla', 'Arrollamiento'), ('embarra', 'Embarracamiento'), ('otro', 'Otro')], max_length=10, null=True, verbose_name='Accidente Vehicular'),
        ),
        migrations.AlterField(
            model_name='uri',
            name='casa_evento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Edif/ Casa'),
        ),
        migrations.AlterField(
            model_name='uri',
            name='enfrentamientoArmado',
            field=models.CharField(blank=True, choices=[('noapli', 'No aplica'), ('blanca', 'Blanca'), ('fuego', 'Fuego'), ('biolo', 'Biológica'), ('Química', 'Química'), ('otro', 'Otro')], help_text='Tipo de Arma', max_length=10, null=True, verbose_name='Enfrentamiento Armado'),
        ),
        migrations.AlterField(
            model_name='uri',
            name='hora',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='uri',
            name='horaLlegadaHosp',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Hora de llegada al Hospital'),
        ),
        migrations.AlterField(
            model_name='uri',
            name='horaSalidaHosp',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Hora de Salida al Hospital'),
        ),
        migrations.AlterField(
            model_name='uri',
            name='hora_alarma',
            field=models.TimeField(verbose_name='Hora de Alarma'),
        ),
        migrations.AlterField(
            model_name='uri',
            name='medico_receptor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Medico que recibe'),
        ),
        migrations.AlterField(
            model_name='uri',
            name='msds',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='MSDS'),
        ),
        migrations.AlterField(
            model_name='uri',
            name='nombre_testigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del Testigo'),
        ),
        migrations.AlterField(
            model_name='uri',
            name='nombrepaciente',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombres del Paciente'),
        ),
        migrations.AlterField(
            model_name='uri',
            name='servicioAsistencial',
            field=models.CharField(blank=True, help_text='Datos del Centro Asistencial donde fue recibido el paciente', max_length=50, null=True, verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='uri',
            name='traumaVehiculo',
            field=models.CharField(blank=True, choices=[('noapli', 'No aplica'), ('automo', 'Automóvil'), ('moto', 'Moto'), ('maquinar', 'Maquinaría'), ('otro', 'Otro')], help_text='Tipo de Vehículo', max_length=9, null=True, verbose_name='Trauma con Vehiculo'),
        ),
    ]
