# Generated by Django 5.1.1 on 2025-03-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potencia', '0002_uri'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoincidencia',
            options={'permissions': [('listar_tipo_incidencia', 'Puede listar tipo incidencia'), ('agregar_tipo_incidencia', 'Puede agregar tipo incidencia'), ('ver_tipo_incidencia', 'Puede ver tipo incidencia'), ('editar_tipo_incidencia', 'Puede actualizar tipo incidencia'), ('eliminar_tipo_incidencia', 'Puede eliminar tipo incidencia')]},
        ),
        migrations.RemoveField(
            model_name='uri',
            name='nombre_apellido',
        ),
        migrations.AddField(
            model_name='uri',
            name='accidenteVehicular',
            field=models.CharField(blank=True, choices=[('positivo', 'Si'), ('negativo', 'No')], max_length=9, null=True, verbose_name='Accidente Vehicular'),
        ),
        migrations.AddField(
            model_name='uri',
            name='alergias',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alergias'),
        ),
        migrations.AddField(
            model_name='uri',
            name='calle_evento',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Calle/Avenida/Carrera'),
        ),
        migrations.AddField(
            model_name='uri',
            name='casa_evento',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Edif/ Casa'),
        ),
        migrations.AddField(
            model_name='uri',
            name='causa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ingreses las causas'),
        ),
        migrations.AddField(
            model_name='uri',
            name='cedulaConductor',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cedula del conductor de la unidad'),
        ),
        migrations.AddField(
            model_name='uri',
            name='cedulaMedico',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cédula del Médico de Guardia'),
        ),
        migrations.AddField(
            model_name='uri',
            name='cedulaSupervisor',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cédula del Supervisor de Guardia'),
        ),
        migrations.AddField(
            model_name='uri',
            name='cedulaTecnico',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cédula del Técnico de emergencias médicas'),
        ),
        migrations.AddField(
            model_name='uri',
            name='cedulaTripulante',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cédula del tercer tripulante'),
        ),
        migrations.AddField(
            model_name='uri',
            name='cedula_acompanante',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cedula del Acompañante'),
        ),
        migrations.AddField(
            model_name='uri',
            name='cedula_testigo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cedula del testigo'),
        ),
        migrations.AddField(
            model_name='uri',
            name='cedulapaciente',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cedula del paciente'),
        ),
        migrations.AddField(
            model_name='uri',
            name='centroAsistencial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uri',
            name='colorPiel',
            field=models.CharField(blank=True, choices=[('pali', 'Pálido'), ('norm', 'Normal')], max_length=9, null=True, verbose_name='Color de la Piel'),
        ),
        migrations.AddField(
            model_name='uri',
            name='conductorUnidad',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Conductor de la unidad'),
        ),
        migrations.AddField(
            model_name='uri',
            name='contacto',
            field=models.CharField(blank=True, choices=[('noncontac', 'No hubo contacto con el paciente'), ('contac', 'Si hubo contacto con el paciente')], max_length=9, null=True, verbose_name='¿Hubo contacto con el paciente?'),
        ),
        migrations.AddField(
            model_name='uri',
            name='descripcion_adic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción Adicional'),
        ),
        migrations.AddField(
            model_name='uri',
            name='descripcion_adic_resp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción Adicional'),
        ),
        migrations.AddField(
            model_name='uri',
            name='direccion_acompanante',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Direccion del acompañante'),
        ),
        migrations.AddField(
            model_name='uri',
            name='direccion_testigo',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Direccion del Testigo'),
        ),
        migrations.AddField(
            model_name='uri',
            name='direccionpaciente',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Direccion del Paciente'),
        ),
        migrations.AddField(
            model_name='uri',
            name='dosis',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dosis'),
        ),
        migrations.AddField(
            model_name='uri',
            name='ecgM',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uri',
            name='ecgO',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uri',
            name='ecgTotal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uri',
            name='ecgV',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uri',
            name='edad_testigo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad del Testigo'),
        ),
        migrations.AddField(
            model_name='uri',
            name='eje_evento',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Eje'),
        ),
        migrations.AddField(
            model_name='uri',
            name='emergenciaMedica',
            field=models.CharField(blank=True, choices=[('aler', 'Alergias'), ('cefa', 'Cefalea'), ('tension', 'Hipo/Hipertensión'), ('gine', 'Gineco-obstetrica'), ('conoci', 'Perdida de Conocimiento'), ('disne', 'Disnea/Dificultad Respiratoria'), ('dolo', 'Dolor'), ('emes', 'Emesis'), ('intox', 'Intoxicaciones'), ('shock', 'Shock no traumatico'), ('inme', 'Inmersión'), ('sca', 'SCA'), ('parad', 'Parada Cardio Respiratoria'), ('convul', 'Convulsiones'), ('hemor', 'Hemorragias no traumaticas'), ('otro', 'Otros')], max_length=9, null=True, verbose_name='Emergencias Médicas no Traumáticas'),
        ),
        migrations.AddField(
            model_name='uri',
            name='empaquetado',
            field=models.CharField(blank=True, choices=[('positivo', 'Si'), ('negativo', 'No')], max_length=9, null=True, verbose_name='Empaquetado de la Herida'),
        ),
        migrations.AddField(
            model_name='uri',
            name='enfrentamientoArmado',
            field=models.CharField(blank=True, choices=[('positivo', 'Si'), ('negativo', 'No')], max_length=9, null=True, verbose_name='Enfrentamiento Armado'),
        ),
        migrations.AddField(
            model_name='uri',
            name='escalaGlasgow',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Escala Glasgow'),
        ),
        migrations.AddField(
            model_name='uri',
            name='estado_evento',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='uri',
            name='evaluacion',
            field=models.CharField(blank=True, choices=[('conscie', 'Consciente'), ('inconsc', 'Inconsciente'), ('viaperme', 'V. A. Permeable'), ('vianope', 'V. A. No Permeable'), ('ovac', 'OVACE'), ('liquid', 'Liquidos/Fluidos'), ('ruido', 'Ruidos en V. A.'), ('rme1', 'Necesita RME')], max_length=9, null=True, verbose_name='Evaluación'),
        ),
        migrations.AddField(
            model_name='uri',
            name='evaluacionResp',
            field=models.CharField(blank=True, choices=[('resp', 'Respira/FR'), ('noresp', 'No Respira'), ('Expsim', 'Expansión Simetrica'), ('expasi', 'Expansión Asimétrica'), ('esresp', 'Esfuerzo Resp. Visible'), ('heris', 'Herida Succionante'), ('estig', 'Estigma de Trauma'), ('desvit', 'Desviación Traqueal'), ('ingur', 'Ingurgitación Yugular'), ('crepo', 'Crepitantes (óseos)'), ('dolo', 'Dolor'), ('enfi', 'Enfisema S.C'), ('reso', 'Resonancia'), ('hipere', 'Hiper-resonancia'), ('mati', 'Matidez'), ('murmu', 'Murmullo Vesicular'), ('ronc', 'Roncus'), ('sibi', 'Sibilancias'), ('crepi', 'Crepitantes'), ('aboli', 'Abolición/Disminución RR')], max_length=20, null=True, verbose_name='Evaluación'),
        ),
        migrations.AddField(
            model_name='uri',
            name='evento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='uri',
            name='fecha_atencion',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='Fecha de Atencion'),
        ),
        migrations.AddField(
            model_name='uri',
            name='firma',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Firma'),
        ),
        migrations.AddField(
            model_name='uri',
            name='foto',
            field=models.CharField(blank=True, choices=[('positivo', 'Si'), ('negativo', 'No')], max_length=9, null=True, verbose_name='¿Hubo registro fotografico?'),
        ),
        migrations.AddField(
            model_name='uri',
            name='fractura',
            field=models.CharField(blank=True, choices=[('positivo', 'Si'), ('negativo', 'No')], max_length=9, null=True, verbose_name='Fracturas'),
        ),
        migrations.AddField(
            model_name='uri',
            name='frecuenciaCardiaca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Frecuencia Cardiaca'),
        ),
        migrations.AddField(
            model_name='uri',
            name='frecuenciaRespiratoria',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Frecuencia Respiratoria'),
        ),
        migrations.AddField(
            model_name='uri',
            name='genero_acompanante',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Genero del acompañante'),
        ),
        migrations.AddField(
            model_name='uri',
            name='generopaciente',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Genero del Paciente'),
        ),
        migrations.AddField(
            model_name='uri',
            name='glicemiaCapilar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Glicemia Capillar'),
        ),
        migrations.AddField(
            model_name='uri',
            name='hemorragia',
            field=models.CharField(blank=True, choices=[('positivo', 'Si'), ('negativo', 'No')], max_length=9, null=True, verbose_name='Hemorragias'),
        ),
        migrations.AddField(
            model_name='uri',
            name='hipotermia',
            field=models.CharField(blank=True, choices=[('positivo', 'Si'), ('negativo', 'No')], max_length=9, null=True, verbose_name='Hipotermia'),
        ),
        migrations.AddField(
            model_name='uri',
            name='hora',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora'),
        ),
        migrations.AddField(
            model_name='uri',
            name='horaLlegadaHosp',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de llegada'),
        ),
        migrations.AddField(
            model_name='uri',
            name='horaMedicion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hora de la Medición'),
        ),
        migrations.AddField(
            model_name='uri',
            name='horaSalidaHosp',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Salida'),
        ),
        migrations.AddField(
            model_name='uri',
            name='hora_alarma',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Alarma'),
        ),
        migrations.AddField(
            model_name='uri',
            name='hora_llegada',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Llegada'),
        ),
        migrations.AddField(
            model_name='uri',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Salida'),
        ),
        migrations.AddField(
            model_name='uri',
            name='hora_sede',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Retorno a la Sede'),
        ),
        migrations.AddField(
            model_name='uri',
            name='hospital',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Llegada al Hospital'),
        ),
        migrations.AddField(
            model_name='uri',
            name='hospitalDestino',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hospital que recibe'),
        ),
        migrations.AddField(
            model_name='uri',
            name='hospitalOrigen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hospital Origen'),
        ),
        migrations.AddField(
            model_name='uri',
            name='humedadPiel',
            field=models.CharField(blank=True, choices=[('sec', 'Seca'), ('hume', 'Húmeda')], max_length=9, null=True, verbose_name='Humedad de la Piel'),
        ),
        migrations.AddField(
            model_name='uri',
            name='institucion',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Institucion'),
        ),
        migrations.AddField(
            model_name='uri',
            name='intervencion',
            field=models.CharField(blank=True, choices=[('freme', 'Frente-Menton'), ('tracc', 'Tracción Mandibular'), ('succ', 'Succión'), ('rme2', 'RME'), ('cof', 'COF'), ('cnf', 'CNF'), ('dgs', 'DSG/TET'), ('vaq', 'VAQ')], max_length=9, null=True, verbose_name='Intervenciones'),
        ),
        migrations.AddField(
            model_name='uri',
            name='intervencionResp',
            field=models.CharField(blank=True, choices=[('ventb', 'Venta. Boca-Barr-Boca'), ('ventco', 'Venta. Con BVM'), ('ventim', 'Ventilación Mecánica'), ('valv', 'Valvula de una vía'), ('parch', 'Parche Oclusivo'), ('descom', 'Descomp. por Aguja'), ('oxige', 'Oxigenoterapia'), ('disp', 'Dispositivo'), ('lpm', 'LPM'), ('otr', 'Otro')], max_length=20, null=True, verbose_name='Intervención'),
        ),
        migrations.AddField(
            model_name='uri',
            name='jefedecomision',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Jefe de Comision'),
        ),
        migrations.AddField(
            model_name='uri',
            name='llenadoCapilar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Llenado Capilar'),
        ),
        migrations.AddField(
            model_name='uri',
            name='lugar_atencion',
            field=models.CharField(blank=True, choices=[('casa', 'Hogar'), ('escue', 'Escuela'), ('calle', 'Via Publica'), ('work', 'Trabajo')], max_length=9, null=True, verbose_name='Lugar de Atención'),
        ),
        migrations.AddField(
            model_name='uri',
            name='maniobraPelvis',
            field=models.CharField(blank=True, choices=[('positivo', 'Si'), ('negativo', 'No')], max_length=9, null=True, verbose_name='Maniobra de Pelvis'),
        ),
        migrations.AddField(
            model_name='uri',
            name='medicamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Medicamento'),
        ),
        migrations.AddField(
            model_name='uri',
            name='medicamentos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Medicamentos'),
        ),
        migrations.AddField(
            model_name='uri',
            name='medicoGuardia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Médico de Guardia'),
        ),
        migrations.AddField(
            model_name='uri',
            name='medicoRefiere',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Medico que refiere'),
        ),
        migrations.AddField(
            model_name='uri',
            name='medico_receptor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uri',
            name='modo_traslado',
            field=models.CharField(blank=True, choices=[('ambula', 'Ambulancia'), ('Vehi', 'Vehiculo Particular'), ('noasist', 'No Asistencial'), ('organ', 'Organismo')], max_length=9, null=True, verbose_name='Modo de Traslado'),
        ),
        migrations.AddField(
            model_name='uri',
            name='msds',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uri',
            name='municipio_evento',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='uri',
            name='nombre_acompanante',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del Acompañante'),
        ),
        migrations.AddField(
            model_name='uri',
            name='nombre_testigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre y Apellido del Testigo'),
        ),
        migrations.AddField(
            model_name='uri',
            name='nombrepaciente',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre y apellido del Paciente'),
        ),
        migrations.AddField(
            model_name='uri',
            name='nroreporte',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Numero de Reporte'),
        ),
        migrations.AddField(
            model_name='uri',
            name='num_interna',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Numeracion Interna'),
        ),
        migrations.AddField(
            model_name='uri',
            name='observacionesSustancia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones de la sustancia'),
        ),
        migrations.AddField(
            model_name='uri',
            name='observaciones_servicio',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Observaciones del Servicios'),
        ),
        migrations.AddField(
            model_name='uri',
            name='organismo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre del Organismo'),
        ),
        migrations.AddField(
            model_name='uri',
            name='otrasHerida',
            field=models.CharField(blank=True, choices=[('positivo', 'Si'), ('negativo', 'No')], max_length=9, null=True, verbose_name='Otras hemorro/heridas'),
        ),
        migrations.AddField(
            model_name='uri',
            name='parentezco_acompanante',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Parentesco del Acompañante'),
        ),
        migrations.AddField(
            model_name='uri',
            name='parroquia_evento',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Parroquia'),
        ),
        migrations.AddField(
            model_name='uri',
            name='piso_evento',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Piso y Apto'),
        ),
        migrations.AddField(
            model_name='uri',
            name='placa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa'),
        ),
        migrations.AddField(
            model_name='uri',
            name='preexistencias',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Preexistencias'),
        ),
        migrations.AddField(
            model_name='uri',
            name='presion',
            field=models.CharField(blank=True, choices=[('positivo', 'Si'), ('negativo', 'No')], max_length=9, null=True, verbose_name='Presión Directa'),
        ),
        migrations.AddField(
            model_name='uri',
            name='presionArterial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Presión Arterial'),
        ),
        migrations.AddField(
            model_name='uri',
            name='pulso',
            field=models.CharField(blank=True, choices=[('positivo', 'Si'), ('negativo', 'No')], max_length=9, null=True, verbose_name='Pulsos distales'),
        ),
        migrations.AddField(
            model_name='uri',
            name='reaccionPupilar',
            field=models.CharField(blank=True, choices=[('isoc', 'Isocórica'), ('anis', 'Anisocoria'), ('mios', 'Miosis'), ('midri', 'Midriasis')], max_length=9, null=True, verbose_name='Reacción Pupilar'),
        ),
        migrations.AddField(
            model_name='uri',
            name='referencia_evento',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Punto de Referencia'),
        ),
        migrations.AddField(
            model_name='uri',
            name='resultado',
            field=models.CharField(blank=True, choices=[('vaperme', 'V. A. Permeabilizada'), ('vadeso', 'V. A. Desobstruida'), ('movesp', 'Mov. Esp. Restrigida'), ('vaisla', 'V. A. Aislada/Asegurada')], max_length=9, null=True, verbose_name='Resultados'),
        ),
        migrations.AddField(
            model_name='uri',
            name='resultadoEvaluacion',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Resultados de la Evaluación Fisica Cefalo Caudal'),
        ),
        migrations.AddField(
            model_name='uri',
            name='resultadoResp',
            field=models.CharField(blank=True, choices=[('venties', 'Ventila espontáneamente'), ('ventia', 'Ventila con Asistencia'), ('neumot', 'Neumotorax resuelto (Abierto o a tensión)'), ('aliv', 'Alivio de la disnea (de origen no traumático)')], max_length=20, null=True, verbose_name='Resultado'),
        ),
        migrations.AddField(
            model_name='uri',
            name='sector_evento',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Sector/Urbanizacion'),
        ),
        migrations.AddField(
            model_name='uri',
            name='selloMsds',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Sellos/MSDS'),
        ),
        migrations.AddField(
            model_name='uri',
            name='servicioAsistencial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uri',
            name='servicio_tipo',
            field=models.CharField(blank=True, choices=[('guardr', 'Guardia de Rutina'), ('guardp', 'Guardia de Prevencion'), ('interhosp', 'Alta/Residencia/Interhospitalario'), ('apoy', 'Apoyo'), ('otr', 'Otro')], max_length=9, null=True, verbose_name='Tipo de Servicio'),
        ),
        migrations.AddField(
            model_name='uri',
            name='signosSintomas',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Signos y Sintomas'),
        ),
        migrations.AddField(
            model_name='uri',
            name='spo2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SPO2'),
        ),
        migrations.AddField(
            model_name='uri',
            name='supervisorGuardia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Supervisor de Guardia'),
        ),
        migrations.AddField(
            model_name='uri',
            name='sustanciaPeligrosa',
            field=models.CharField(blank=True, choices=[('positivo', 'Si'), ('negativo', 'No')], max_length=9, null=True, verbose_name='Sustancia Peligrosa'),
        ),
        migrations.AddField(
            model_name='uri',
            name='tecnicoEmergencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Técnico de emergencias médicas'),
        ),
        migrations.AddField(
            model_name='uri',
            name='telefono_acompanate',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Numero de Telefono del Acompañante'),
        ),
        migrations.AddField(
            model_name='uri',
            name='telefono_testigo',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Numero de Telefono del Testigo'),
        ),
        migrations.AddField(
            model_name='uri',
            name='telefonopaciente',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Numero de Telefono del Paciente'),
        ),
        migrations.AddField(
            model_name='uri',
            name='temperatura',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Temperatura'),
        ),
        migrations.AddField(
            model_name='uri',
            name='temperaturaPiel',
            field=models.CharField(blank=True, choices=[('fria', 'Fría'), ('tibi', 'Tibia')], max_length=9, null=True, verbose_name='Temperatura de la Piel'),
        ),
        migrations.AddField(
            model_name='uri',
            name='tercerTripulante',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tercer Tripulante'),
        ),
        migrations.AddField(
            model_name='uri',
            name='tiempo_servicio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tiempo de Servicio'),
        ),
        migrations.AddField(
            model_name='uri',
            name='tipounidad',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo de Unidad'),
        ),
        migrations.AddField(
            model_name='uri',
            name='torniquete',
            field=models.CharField(blank=True, choices=[('positivo', 'Si'), ('negativo', 'No')], max_length=9, null=True, verbose_name='Torniquete'),
        ),
        migrations.AddField(
            model_name='uri',
            name='transferencia_emergencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Transferencia al Servicio de Emergencia'),
        ),
        migrations.AddField(
            model_name='uri',
            name='trasladoIncial',
            field=models.CharField(blank=True, choices=[('positivo', 'Si'), ('negativo', 'No')], max_length=9, null=True, verbose_name='¿El paciente fue referido del centro asistencial al que fue trasladado inicialmente?'),
        ),
        migrations.AddField(
            model_name='uri',
            name='traumaNoIntencional',
            field=models.CharField(blank=True, choices=[('caipie', 'Caida de Propio Pie'), ('caialtu', 'Caida de Altura'), ('quemad', 'Quemadura'), ('morde', 'Mordedura'), ('otr', 'Otros')], max_length=9, null=True, verbose_name='Trauma no Intencional'),
        ),
        migrations.AddField(
            model_name='uri',
            name='traumaVehiculo',
            field=models.CharField(blank=True, choices=[('positivo', 'Si'), ('negativo', 'No')], max_length=9, null=True, verbose_name='Trauma con Vehiculo'),
        ),
        migrations.AddField(
            model_name='uri',
            name='ultimaComida',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Última comida'),
        ),
        migrations.AddField(
            model_name='uri',
            name='unidad_placa',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Unidad/Placa'),
        ),
        migrations.AddField(
            model_name='uri',
            name='via_reporte',
            field=models.CharField(blank=True, choices=[('rs', 'RRSS'), ('rad', 'Radio'), ('casu', 'Casual'), ('telef', 'Telefonico'), ('otr', 'Otro')], max_length=9, null=True, verbose_name='Vía del Reporte'),
        ),
        migrations.AddField(
            model_name='uri',
            name='viajaba',
            field=models.CharField(blank=True, choices=[('conduc', 'Conductor'), ('tripul', 'Tripulante')], max_length=9, null=True, verbose_name='Viajaba como'),
        ),
    ]
