# Generated by Django 5.1.1 on 2025-03-29 18:44

import django.core.validators
import django.db.models.deletion
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potencia', '0003_alter_incidencia_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(choices=[('1', 'Amazonas'), ('2', 'Anzoátegui'), ('3', 'Apure'), ('4', 'Aragua'), ('5', 'Barinas'), ('6', 'Bolívar'), ('7', 'Carabobo'), ('8', 'Cojedes'), ('9', 'Delta Amacuro'), ('10', 'Falcón'), ('11', 'Guárico'), ('12', 'Lara'), ('13', 'Mérida'), ('14', 'Miranda'), ('15', 'Monagas'), ('16', 'Nueva Esparta'), ('17', 'Portuguesa'), ('18', 'Sucre'), ('19', 'Táchira'), ('20', 'Trujillo'), ('21', 'Vargas'), ('22', 'Yaracuy'), ('23', 'Zulia'), ('24', 'Distrito Capital')], max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='observaciones',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(2800), helpers.validForm.TextValidator()], verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='tipo_incidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='potencia.tipoincidencia', verbose_name='Tipo de incidencia'),
        ),
        migrations.AlterField(
            model_name='tipoincidencia',
            name='tipo',
            field=models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(120), helpers.validForm.TextValidator()], verbose_name='Tipo de Incidencia'),
        ),
    ]
