# Generated by Django 5.1.1 on 2025-05-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="averia",
            name="ubicacion",
        ),
        migrations.AddField(
            model_name="averia",
            name="d_averia",
            field=models.CharField(
                choices=[
                    ("2", "Gestión Humana"),
                    ("3", "Gestión Administrativa"),
                    ("12", "Tecnología Comunicación e Información"),
                ],
                default="Desconocido",
                max_length=13,
                verbose_name="Depertamento que reporta Averia",
            ),
        ),
    ]
