# Generated by Django 5.1.1 on 2025-04-07 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoarticulo',
            options={'ordering': ['-id'], 'permissions': [('listar_tipo_articulo', 'Puede listar tipos de articulos'), ('agregar_tipo_articulo', 'Puede agregar tipo de articulo'), ('ver_tipo_articulo', 'Puede ver tipo de articulo'), ('editar_tipo_articulo', 'Puede actualizar tipo de articulo'), ('eliminar_tipo_articulo', 'Puede eliminar tipo de articulo')], 'verbose_name': 'Tipo de Articulo', 'verbose_name_plural': 'Tipos de Articulos'},
        ),
    ]
