# Generated by Django 5.1.1 on 2025-04-06 23:22

import django.core.validators
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='observaciones',
            field=models.TextField(max_length=255, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(255), helpers.validForm.TextValidator()]),
        ),
        migrations.AlterField(
            model_name='compra',
            name='n_orden',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1)], verbose_name='N° de orden'),
        ),
    ]
