# Generated by Django 5.1.1 on 2025-03-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='condicion',
            field=models.CharField(blank=True, choices=[('N', 'Nuevo'), ('U', 'Usado'), ('D', 'Deteriorado'), ('-', 'No Aplica')], default='-', max_length=1, null=True, verbose_name='Condición'),
        ),
    ]
