# Generated by Django 5.1.1 on 2025-04-18 00:01

import django.core.validators
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='averia',
            options={'ordering': ['-created_at'], 'permissions': [('listar_averia', 'Puede listar averías'), ('agregar_averia', 'Puede agregar avería'), ('ver_averia', 'Puede ver avería'), ('editar_averia', 'Puede editar avería'), ('eliminar_averia', 'Puede eliminar avería')], 'verbose_name': 'Avería', 'verbose_name_plural': 'Averías'},
        ),
        migrations.AddField(
            model_name='averia',
            name='observaciones',
            field=models.TextField(max_length=180, null=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(180), helpers.validForm.TextValidator()], verbose_name='Observaciones'),
        ),
        migrations.AlterModelTable(
            name='averia',
            table='administracion_averia',
        ),
    ]
