# Generated by Django 5.1.1 on 2025-01-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='asignado',
            field=models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=8),
        ),
    ]
