# Generated by Django 5.1.1 on 2025-03-22 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacion',
            options={'ordering': ['-id'], 'permissions': [('listar_asignacion', 'Puede listar asignaciones'), ('agregar_asignacion', 'Puede agregar asignacion'), ('ver_asignacion', 'Puede ver asignacion'), ('editar_asignacion', 'Puede actualizar asignacion'), ('eliminar_asignacion', 'Puede eliminar asignacion')], 'verbose_name': 'Asignacion', 'verbose_name_plural': 'Asignaciones'},
        ),
        migrations.AlterModelOptions(
            name='sede',
            options={'permissions': [('listar_sede', 'Puede listar sedes'), ('agregar_sede', 'Puede agregar sede'), ('ver_sede', 'Puede ver sede'), ('editar_sede', 'Puede actualizar sede'), ('eliminar_sede', 'Puede eliminar sede')], 'verbose_name': 'sede', 'verbose_name_plural': 'sedes'},
        ),
    ]
