# Generated by Django 5.1.1 on 2025-03-30 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_articulo_condicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='n_orden',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='N° de orden'),
        ),
    ]
