# Generated by Django 5.1.1 on 2025-05-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_remove_averia_ubicacion_averia_d_averia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averia',
            name='d_averia',
            field=models.CharField(choices=[('1', 'Asesoría Jurídica'), ('2', 'Gestión Humana'), ('3', 'Gestión Administrativa'), ('4', 'Unidad de Respuesta Inmediata'), ('5', 'Potencia'), ('6', 'Organización'), ('7', 'Presupuestos'), ('8', 'Planificación'), ('9', 'Protección y Seguridad Integral'), ('10', 'Biblioteca de Manuales'), ('11', 'Operaciones'), ('12', 'Tecnología Comunicación e Información'), ('13', 'Gestion Comunicacional')], max_length=13, verbose_name='Depertamento que reporta Averia'),
        ),
    ]
