# Generated by Django 5.1.1 on 2025-03-01 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_articulo_asignado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='averia',
            options={'permissions': [('listar_averia', 'Puede listar averias'), ('agregar_averia', 'Puede agregar averia'), ('ver_averia', 'Puede ver averia'), ('editar_averia', 'Puede actualizar averia'), ('eliminar_averia', 'Puede eliminar averia')]},
        ),
        migrations.AlterModelOptions(
            name='compra',
            options={'permissions': [('listar_compra', 'Puede listar compras'), ('agregar_compra', 'Puede agregar compra'), ('ver_compra', 'Puede ver compra'), ('editar_compra', 'Puede actualizar compra'), ('eliminar_compra', 'Puede eliminar compra')]},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'permissions': [('listar_departamento', 'Puede listar departamentos'), ('agregar_departamento', 'Puede agregar departamento'), ('ver_departamento', 'Puede ver departamento'), ('editar_departamento', 'Puede actualizar departamento'), ('eliminar_departamento', 'Puede eliminar departamento')]},
        ),
        migrations.AlterModelOptions(
            name='tipoaveria',
            options={'permissions': [('listar_tipo_averia', 'Puede listar tipos de averias'), ('agregar_tipo_averia', 'Puede agregar tipo de averia'), ('ver_tipo_averia', 'Puede ver tipo de averia'), ('editar_tipo_averia', 'Puede actualizar tipo de averia'), ('eliminar_tipo_averia', 'Puede eliminar tipo de averia')]},
        ),
    ]
