# Generated by Django 5.1.1 on 2025-04-07 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_tipoarticulo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['-fecha_adq'], 'permissions': [('listar_articulo', 'Puede listar articulos'), ('agregar_articulo', 'Puede agregar articulo'), ('ver_articulo', 'Puede ver articulo'), ('editar_articulo', 'Puede actualizar articulo'), ('eliminar_articulo', 'Puede eliminar articulo')], 'verbose_name': 'Actividad social', 'verbose_name_plural': 'Actividades sociales'},
        ),
    ]
