# Generated by Django 5.1.1 on 2025-03-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_asignacion_options_alter_sede_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='valor_bs',
            field=models.TextField(max_length=255),
        ),
    ]
