# Generated by Django 5.1.1 on 2025-03-29 18:44

import django.core.validators
import django.db.models.deletion
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_alter_compra_valor_bs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='cantidad',
            field=models.IntegerField(help_text='La cantidad debe ser un número entero positivo.', validators=[django.core.validators.MinValueValidator(1), helpers.validForm.PositiveIntegerValidator()], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='cantidad_combustible',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de combustible máx. (En litros)'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='codigo_bn',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(255), helpers.validForm.TextValidator()], verbose_name='Código BN'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='condicion',
            field=models.CharField(choices=[('N', 'Nuevo'), ('U', 'Usado'), ('D', 'Deteriorado')], max_length=1, verbose_name='Condición'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='descripcion',
            field=models.TextField(max_length=255, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(255), helpers.validForm.TextValidator()], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='fecha_adq',
            field=models.DateField(verbose_name='Fecha de adquisición'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='marca',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(120), helpers.validForm.TextValidator()], verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='modelo',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(120), helpers.validForm.TextValidator()], verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='placa',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(255), helpers.validForm.TextValidator()], verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='serial',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(255), helpers.validForm.TextValidator()], verbose_name='Serial'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='cantidad',
            field=models.IntegerField(help_text='La cantidad debe ser un número entero positivo.', validators=[django.core.validators.MinValueValidator(1), helpers.validForm.PositiveIntegerValidator()]),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='descripcion',
            field=models.TextField(max_length=255, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(255), helpers.validForm.TextValidator()]),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='observaciones',
            field=models.TextField(max_length=255, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(255), helpers.validForm.TextValidator()]),
        ),
        migrations.AlterField(
            model_name='averia',
            name='codigo_bn',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(255), helpers.validForm.TextValidator()], verbose_name='Código BN'),
        ),
        migrations.AlterField(
            model_name='averia',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='averia',
            name='problema',
            field=models.TextField(max_length=255, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(255), helpers.validForm.TextValidator()], verbose_name='Problema'),
        ),
        migrations.AlterField(
            model_name='averia',
            name='serial',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(255), helpers.validForm.UnicodeAlphaSpaceValidator(extra_chars='-')], verbose_name='Serial'),
        ),
        migrations.AlterField(
            model_name='averia',
            name='tipo_averia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.tipoaveria', verbose_name='Tipo de avería'),
        ),
        migrations.AlterField(
            model_name='averia',
            name='ubicacion',
            field=models.TextField(max_length=255, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(255), helpers.validForm.TextValidator()], verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.articulo', verbose_name='Artículo'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='n_orden',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(255), helpers.validForm.UnicodeAlphaSpaceValidator(extra_chars='-')], verbose_name='N° de orden'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='valor_bs',
            field=models.TextField(max_length=255, verbose_name='Valor en BS'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(255), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='estatus',
            field=models.CharField(choices=[('act', 'Activo'), ('rem', 'Remodelacion'), ('cer', 'Cerrada')], max_length=3, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='sede',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(30), helpers.validForm.TextValidator()], verbose_name='Sede'),
        ),
    ]
