# Generated by Django 5.1.1 on 2025-04-05 20:20

import django.core.validators
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_alter_compra_n_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'permissions': [('listar_departamento', 'Puede listar departamentos'), ('agregar_departamento', 'Puede agregar departamentos'), ('ver_departamento', 'Puede ver detalles de departamentos'), ('editar_departamento', 'Puede editar departamentos'), ('eliminar_departamento', 'Puede eliminar departamentos')]},
        ),
        migrations.AlterField(
            model_name='articulo',
            name='cantidad_combustible',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), helpers.validForm.PositiveIntegerValidator()], verbose_name='Cantidad de combustible máx. (En litros)'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='n_orden',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), helpers.validForm.PositiveIntegerValidator()], verbose_name='N° de orden'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='estatus',
            field=models.CharField(choices=[('act', 'Activo'), ('rem', 'En remodelación'), ('cer', 'Cerrado')], max_length=3, verbose_name='Estatus'),
        ),
    ]
