# Generated by Django 5.1.1 on 2025-03-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_alter_compra_valor_bs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='n_orden',
            field=models.TextField(max_length=255),
        ),
    ]
