# Generated by Django 5.1.1 on 2025-03-29 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_alter_articulo_cantidad_and_more'),
        ('administracion', '0004_alter_compra_n_orden'),
    ]

    operations = [
    ]
