# Generated by Django 5.1.1 on 2025-03-30 18:11

import django.core.validators
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_merge_20250329_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='codigo_bn',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(30), helpers.validForm.TextValidator()], verbose_name='Código BN'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='marca',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(120), helpers.validForm.TextValidator()], verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='modelo',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(120), helpers.validForm.TextValidator()], verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='placa',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(10), helpers.validForm.TextValidator()], verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='serial',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(30), helpers.validForm.TextValidator()], verbose_name='Serial'),
        ),
        migrations.AlterField(
            model_name='averia',
            name='codigo_bn',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(30), helpers.validForm.TextValidator()], verbose_name='Código BN'),
        ),
        migrations.AlterField(
            model_name='averia',
            name='problema',
            field=models.TextField(max_length=180, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(180), helpers.validForm.TextValidator()], verbose_name='Problema'),
        ),
        migrations.AlterField(
            model_name='averia',
            name='serial',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(30), helpers.validForm.UnicodeAlphaSpaceValidator(extra_chars='-')], verbose_name='Serial'),
        ),
        migrations.AlterField(
            model_name='averia',
            name='ubicacion',
            field=models.TextField(max_length=180, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(180), helpers.validForm.TextValidator()], verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='valor_bs',
            field=models.TextField(validators=[helpers.validForm.CurrencyValidator()], verbose_name='Valor en BS'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(30), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Departamento'),
        ),
    ]
