# Generated by Django 5.1.1 on 2025-03-29 22:33

import django.core.validators
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_merge_20250329_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='n_orden',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(255), helpers.validForm.UnicodeAlphaSpaceValidator(extra_chars='-')], verbose_name='N° de orden'),
        ),
    ]
