# Generated by Django 5.1.1 on 2025-03-29 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_alter_compra_n_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='n_orden',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100000000), django.core.validators.MaxValueValidator(999999999)], verbose_name='N° de orden'),
        ),
    ]
