# Generated by Django 5.1.1 on 2025-03-29 22:49

import django.core.validators
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_alter_compra_n_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averia',
            name='problema',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(255), helpers.validForm.TextValidator()], verbose_name='Problema'),
        ),
        migrations.AlterField(
            model_name='averia',
            name='ubicacion',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(255), helpers.validForm.TextValidator()], verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='n_orden',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)], verbose_name='N° de orden'),
        ),
    ]
