# Generated by Django 5.0.6 on 2024-06-03 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Equipo')),
                ('description', models.TextField(verbose_name='Descripción del equipo')),
                ('status', models.CharField(choices=[('available', 'Available'), ('loaned', 'Loaned'), ('maintenance', 'Maintenance')], max_length=50, verbose_name='Estatus del equipo')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaAccountEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Twitter', 'Twitter')], max_length=50, verbose_name='Plataforma')),
                ('username', models.CharField(max_length=60, verbose_name='Nombre de usuario')),
                ('url', models.URLField(verbose_name='Direccion web')),
                ('followers', models.PositiveSmallIntegerField(verbose_name='Seguidores')),
                ('responsible', models.CharField(max_length=100, verbose_name='Quien administra la red')),
                ('publications', models.PositiveSmallIntegerField(verbose_name='Publicaciones')),
            ],
            options={
                'db_table': 'social_media_accounts',
            },
        ),
        migrations.CreateModel(
            name='EquipmentLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100, verbose_name='Departamento')),
                ('loan_date', models.DateField(verbose_name='Fecha del préstamo')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Fecha de devolución')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gc.equipment', verbose_name='Equipo ID')),
            ],
        ),
    ]
