# Generated by Django 5.1.1 on 2025-04-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='discapacitado',
            field=models.CharField(choices=[(True, 'si'), (False, 'no')], default=False, max_length=6),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estudia',
            field=models.CharField(choices=[(True, 'si'), (False, 'no')], default=False, max_length=6),
        ),
    ]
