# Generated by Django 5.1.1 on 2025-04-17 20:49

import django.core.validators
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='cargo',
            field=models.CharField(max_length=60, unique=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(60), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Nombre del Cargo'),
        ),
    ]
