# Generated by Django 5.1.1 on 2025-03-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'permissions': [('listar_cargo', 'Puede listar cargos'), ('agregar_cargo', 'Puede agregar cargo'), ('ver_cargo', 'Puede ver cargo'), ('editar_cargo', 'Puede actualizar cargo'), ('eliminar_cargo', 'Puede eliminar cargo'), ('exel_cargo', 'Puede exportar cargo a excel')], 'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='contrato',
            options={'permissions': [('listar_contrato', 'Puede listar contratos'), ('agregar_contrato', 'Puede agregar contrato'), ('ver_contrato', 'Puede ver contrato'), ('editar_contrato', 'Puede actualizar contrato'), ('eliminar_contrato', 'Puede eliminar contrato'), ('exel_contrato', 'Puede exportar contrato a excel')], 'verbose_name': 'contrato', 'verbose_name_plural': 'contratos'},
        ),
        migrations.AlterModelOptions(
            name='cuenta',
            options={'permissions': [('listar_cuenta', 'Puede listar cuentas'), ('agregar_cuenta', 'Puede agregar cuenta'), ('ver_cuenta', 'Puede ver cuenta'), ('editar_cuenta', 'Puede actualizar cuenta'), ('eliminar_cuenta', 'Puede eliminar cuenta'), ('exel_cuenta', 'Puede exportar cuenta a excel')], 'verbose_name': 'cuenta', 'verbose_name_plural': 'cuentas'},
        ),
        migrations.AlterModelOptions(
            name='dotacion',
            options={'permissions': [('listar_dotacion', 'Puede listar dotacion'), ('agregar_dotacion', 'Puede agregar dotacion'), ('ver_dotacion', 'Puede ver dotacion'), ('editar_dotacion', 'Puede actualizar dotacion'), ('eliminar_dotacion', 'Puede eliminar dotacion'), ('exel_dotacion', 'Puede exportar dotacion a excel')], 'verbose_name': 'dotacion', 'verbose_name_plural': 'dotaciones'},
        ),
        migrations.AlterModelOptions(
            name='educacion',
            options={'permissions': [('listar_educacion', 'Puede listar educacion'), ('agregar_educacion', 'Puede agregar educacion'), ('ver_educacion', 'Puede ver educacion'), ('editar_educacion', 'Puede actualizar educacion'), ('eliminar_educacion', 'Puede eliminar educacion'), ('exel_educacion', 'Puede exportar educacion a excel')], 'verbose_name': 'educacion', 'verbose_name_plural': 'educaciones'},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'permissions': [('listar_empleado', 'Puede listar empleados'), ('agregar_empleado', 'Puede agregar empleado'), ('ver_empleado', 'Puede ver empleado'), ('editar_empleado', 'Puede actualizar empleado'), ('eliminar_empleado', 'Puede eliminar empleado'), ('exel_empleado', 'Puede exportar empleado a excel')], 'verbose_name': 'empleado', 'verbose_name_plural': 'empleados'},
        ),
        migrations.AlterModelOptions(
            name='familiar',
            options={'permissions': [('listar_familiares', 'Listar familiares'), ('agregar_familiar', 'Agregar familiares'), ('ver_familiar', 'Ver familiares'), ('modificar_familiar', 'Modificar familiares'), ('eliminar_familiar', 'Eliminar familiares'), ('exel_familiar', 'Exportar familiares a excel')], 'verbose_name': 'familiar', 'verbose_name_plural': 'familiares'},
        ),
        migrations.AlterModelOptions(
            name='sueldo',
            options={'permissions': [('listar_sueldos', 'Listar sueldos'), ('agregar_sueldo', 'Agregar sueldos'), ('ver_sueldo', 'Ver sueldos'), ('modificar_sueldo', 'Modificar sueldos'), ('eliminar_sueldo', 'Eliminar sueldos'), ('exel_sueldo', 'Exportar sueldos a excel')], 'verbose_name': 'sueldo', 'verbose_name_plural': 'sueldos'},
        ),
        migrations.AlterModelOptions(
            name='sueldoempleado',
            options={'permissions': [('listar_sueldos', 'Listar sueldos'), ('agregar_sueldo', 'Agregar sueldos'), ('ver_sueldo', 'Ver sueldos'), ('modificar_sueldo', 'Modificar sueldos'), ('eliminar_sueldo', 'Eliminar sueldos'), ('exel_sueldo', 'Exportar sueldos a excel')], 'verbose_name': 'detalles del sueldo', 'verbose_name_plural': 'destalles de los sueldos'},
        ),
        migrations.AlterModelOptions(
            name='tipoempleado',
            options={'permissions': [('listar_tipo_empleados', 'Listar tipos de empleados'), ('agregar_tipo_empleado', 'Agregar tipos de empleados'), ('ver_tipo_empleado', 'Ver tipos de empleados'), ('modificar_tipo_empleado', 'Modificar tipos de empleados'), ('eliminar_tipo_empleado', 'Eliminar tipos de empleados'), ('exel_tipo_empleado', 'Exportar tipos de empleados a excel')], 'verbose_name': 'tipo de empleado', 'verbose_name_plural': 'tipos de empleados'},
        ),
        migrations.AlterModelOptions(
            name='tiposueldo',
            options={'permissions': [('listar_tipo_sueldos', 'Listar tipos de sueldos'), ('agregar_tipo_sueldo', 'Agregar tipos de sueldos'), ('ver_tipo_sueldo', 'Ver tipos de sueldos'), ('modificar_tipo_sueldo', 'Modificar tipos de sueldos'), ('eliminar_tipo_sueldo', 'Eliminar tipos de sueldos'), ('exel_tipo_sueldo', 'Exportar tipos de sueldos a excel')], 'verbose_name': 'tipo de empleado', 'verbose_name_plural': 'tipos de empleados'},
        ),
        migrations.AlterField(
            model_name='contrato',
            name='comision_servicio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fasmij',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pnb',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='discapacitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estudia',
            field=models.BooleanField(default=False),
        ),
    ]
