# Generated by Django 5.1.1 on 2025-03-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_alter_cargo_options_alter_contrato_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
