# Generated by Django 5.1.1 on 2025-04-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_alter_empleado_discapacitado_alter_empleado_estudia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='comision_servicio',
            field=models.CharField(choices=[(True, 'si'), (False, 'no')], default=(False, 'no'), max_length=2),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fasmij',
            field=models.CharField(choices=[(True, 'si'), (False, 'no')], default=(False, 'no'), max_length=2),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pnb',
            field=models.CharField(choices=[(True, 'si'), (False, 'no')], default=(False, 'no'), max_length=2),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='discapacitado',
            field=models.CharField(choices=[(True, 'si'), (False, 'no')], default=(False, 'no'), max_length=2),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estudia',
            field=models.CharField(choices=[(True, 'si'), (False, 'no')], default=(False, 'no'), max_length=2),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='discapacidad',
            field=models.BooleanField(choices=[(True, 'si'), (False, 'no')], default=(False, 'no'), verbose_name='Discapacidad'),
        ),
    ]
