# Generated by Django 5.1.1 on 2025-05-21 21:56

import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_alter_familiar_apellidos_alter_familiar_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposueldo',
            name='monto',
            field=models.TextField(validators=[helpers.validForm.CurrencyValidator()], verbose_name='Monto Asignado'),
        ),
    ]
