# Generated by Django 5.1.1 on 2025-04-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0003_alter_contrato_comision_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='comision_servicio',
            field=models.BooleanField(choices=[(True, 'si'), (False, 'no')], default=(False, 'no'), verbose_name='Comision Servicio'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fasmij',
            field=models.BooleanField(choices=[(True, 'si'), (False, 'no')], default=(False, 'no'), verbose_name='Fasmij'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pnb',
            field=models.BooleanField(choices=[(True, 'si'), (False, 'no')], default=(False, 'no'), verbose_name='PNB'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='discapacitado',
            field=models.BooleanField(choices=[(True, 'si'), (False, 'no')], default=(False, 'no'), verbose_name='Discapacitado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estudia',
            field=models.BooleanField(choices=[(True, 'si'), (False, 'no')], default=(False, 'no'), verbose_name='Estudia'),
        ),
    ]
