# Generated by Django 5.1.1 on 2025-03-29 18:44

import django.core.validators
import django.db.models.deletion
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_alter_articulo_cantidad_and_more'),
        ('rrhh', '0003_alter_empleado_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='cargo',
            field=models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(60), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Nombre del Cargo'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='estatus',
            field=models.CharField(choices=[('act', 'Activo'), ('ina', 'Inactivo'), ('inv', 'Invalido'), ('cer', 'Cerrado')], max_length=3, verbose_name='Estado del Cargo'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.cargo', verbose_name='Cargo asignado'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='comision_servicio',
            field=models.BooleanField(default=False, verbose_name='Comision servicio'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.empleado', verbose_name='Nombre del empleado'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_culminacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de culminacion'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_ingreso',
            field=models.DateField(verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_ingreso_911',
            field=models.DateField(verbose_name='Fecha de ingreso al Ven-911'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_ingreso_apn',
            field=models.DateField(verbose_name='Fecha de ingreso APN'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pnb',
            field=models.BooleanField(default=False, verbose_name='Funcionario PNB'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.sede', verbose_name='Sede'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo',
            field=models.CharField(choices=[('pasante', 'Pasante'), ('prueba', 'Periodo de Prueba'), ('contrato', 'Contratado'), ('fijo', 'Personal Fijo')], max_length=8, verbose_name='Tipo de contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo_personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.tipoempleado', verbose_name='Tipo de personal'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.empleado', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='numero_cuenta',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(30), helpers.validForm.TextValidator()], verbose_name='Número de cuenta'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='pago_movil',
            field=models.BooleanField(verbose_name='¿Activar pago móvil?'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(20), helpers.validForm.PhoneNumberValidator()], verbose_name='Teléfono móvil'),
        ),
        migrations.AlterField(
            model_name='dotacion',
            name='camisa',
            field=models.CharField(choices=[('XS', 'Extra Pequena'), ('S', 'Pequena'), ('M', 'Mediana'), ('L', 'Grande'), ('XL', 'Extra Grande')], max_length=2, verbose_name='Talla de Camisa'),
        ),
        migrations.AlterField(
            model_name='dotacion',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.empleado', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='dotacion',
            name='pantalon',
            field=models.CharField(choices=[('8', 'Extra Pequena (Dama)'), ('10', 'Pequena (Dama)'), ('12', 'Mediana (Dama)'), ('14', 'Grande (Dama)'), ('16', 'Extra Grande (Dama)'), ('18', 'Super Grande (Dama)'), ('20', 'Gigante (Dama)'), ('28', 'Extra Pequena (Caballero)'), ('30', 'Pequena (Caballero)'), ('32', 'Mediana (Caballero)'), ('34', 'Grande (Caballero)'), ('36', 'Extra Grande (Caballero)'), ('38', 'Super Grande (Caballero)'), ('40', 'Gigante (Caballero)'), ('42', 'Extra Gigante (Caballero)')], max_length=2, verbose_name='Talla de Pantalón'),
        ),
        migrations.AlterField(
            model_name='dotacion',
            name='zapato',
            field=models.CharField(choices=[('33', 'Talla 33'), ('34', 'Talla 34'), ('35', 'Talla 35'), ('36', 'Talla 36'), ('37', 'Talla 37'), ('38', 'Talla 38'), ('39', 'Talla 39'), ('40', 'Talla 40'), ('41', 'Talla 41'), ('42', 'Talla 42'), ('43', 'Talla 43'), ('44', 'Talla 44'), ('45', 'Talla 45'), ('46', 'Talla 46')], max_length=2, verbose_name='Talla de Zapato'),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='area_conocimiento',
            field=models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(120), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Área de Conocimiento'),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='codigo_titulo',
            field=models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(120), helpers.validForm.TextValidator()], verbose_name='Código del Título'),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='colegio',
            field=models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(120), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Nombre del colegio'),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.empleado', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='enlace_certificado',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(120), helpers.validForm.TextValidator()], verbose_name='Enlace al Certificado'),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='fecha_culminacion',
            field=models.DateField(verbose_name='Fecha de culminacion'),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='titulo',
            field=models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(120), helpers.validForm.TextValidator()], verbose_name='Titulo obtenido'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apellidos',
            field=models.CharField(max_length=90, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(90), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Apellidos del empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(max_length=15, unique=True, verbose_name='Cedula de identidad'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='contratos',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(180), helpers.validForm.PositiveIntegerValidator()], verbose_name='Cantidad de contratos'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(max_length=180, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(180), helpers.validForm.TextValidator()]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nacionalidad',
            field=models.CharField(choices=[('ve', 'Venezolano'), ('ex', 'Extranjero')], max_length=2, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombres',
            field=models.CharField(max_length=90, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(90), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Nombres del empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sexo',
            field=models.CharField(choices=[('f', 'Femenino'), ('m', 'Masculino')], max_length=1, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(20), helpers.validForm.PhoneNumberValidator()], verbose_name='Telefono del empleado'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='apellidos',
            field=models.CharField(max_length=90, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(90), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Apellidos del Familiar'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='cedula',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cedula de identidad'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='discapacidad',
            field=models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=8, verbose_name='Discapacidad'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.empleado', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='estado_civil',
            field=models.CharField(choices=[('s', 'Soltero'), ('c', 'Casado'), ('d', 'Divorviado'), ('v', 'Viudo')], max_length=1, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='nombres',
            field=models.CharField(max_length=90, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(90), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Nombres del Familiar'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='observacion',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(150), helpers.validForm.TextValidator()], verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='parentezco',
            field=models.CharField(choices=[('hermano', 'Hermana|Hermano'), ('pareja', 'Conyugue'), ('mama', 'Madre'), ('papa', 'Padre'), ('hijo', 'Hija|Hijo')], max_length=7, verbose_name='Parentezco'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='sexo',
            field=models.CharField(choices=[('f', 'Femenino'), ('m', 'Masculino')], max_length=1, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='tipo_hijo',
            field=models.CharField(blank=True, choices=[('menor_12', 'Hijo menor de 12'), ('hijos_13_18', 'Hijo entre 13 y 18'), ('mayor_18', 'Hijo mayor de 18')], max_length=11, null=True, verbose_name='Tipo de hijo'),
        ),
        migrations.AlterField(
            model_name='tipoempleado',
            name='estatus',
            field=models.CharField(choices=[('act', 'Activo'), ('ina', 'Inactivo'), ('inv', 'Invalido'), ('cer', 'Cerrado')], max_length=3, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='tipoempleado',
            name='tipo_personal',
            field=models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(255), helpers.validForm.TextValidator()], verbose_name='Tipo de personal'),
        ),
        migrations.AlterField(
            model_name='tiposueldo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(255), helpers.validForm.TextValidator()], verbose_name='Descripción Detallada'),
        ),
        migrations.AlterField(
            model_name='tiposueldo',
            name='estatus',
            field=models.CharField(choices=[('act', 'Activo'), ('sup', 'Suspendido')], max_length=3, verbose_name='Estado Actual'),
        ),
        migrations.AlterField(
            model_name='tiposueldo',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Asignado'),
        ),
        migrations.AlterField(
            model_name='tiposueldo',
            name='tipo',
            field=models.CharField(choices=[('ticket', 'Cesta Ticket'), ('guerra', 'Bono de Guerra'), ('discapacidad', 'Prima por discapacidad'), ('menor_12', 'Prima por dependecias menores de 12'), ('hijos_13_18', 'Prima por dependecias menores de 13 a 18'), ('hijos_discapacidad', 'Prima por dependecias menores con discapacidad'), ('profesionalismo', 'Prima por Profesionalismo'), ('minimo', 'Sueldo Minimo')], max_length=21, verbose_name='Tipo de Sueldo'),
        ),
    ]
