# Generated by Django 5.1.1 on 2025-04-06 23:22

import django.core.validators
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0004_alter_contrato_comision_servicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='fasmij',
        ),
        migrations.AlterField(
            model_name='contrato',
            name='comision_servicio',
            field=models.BooleanField(choices=[(True, 'si'), (False, 'no')], default=(False, 'no'), verbose_name='Comision servicio'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pnb',
            field=models.BooleanField(choices=[(True, 'si'), (False, 'no')], default=(False, 'no'), verbose_name='Funcionario PNB'),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='colegio',
            field=models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(120), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Nombre del Colegio'),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='titulo',
            field=models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(120), helpers.validForm.TextValidator()], verbose_name='Titulo Obtenido'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apellidos',
            field=models.CharField(max_length=90, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(90), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Apellidos del Empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(14), helpers.validForm.CedulaVenezolanaValidator()], verbose_name='Cédula de Identidad'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(max_length=180, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(180), helpers.validForm.TextValidator()], verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='discapacitado',
            field=models.BooleanField(choices=[(True, 'si'), (False, 'no')], default=(False, 'no')),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estado_civil',
            field=models.CharField(choices=[('s', 'Soltero'), ('c', 'Casado'), ('d', 'Divorviado'), ('v', 'Viudo')], max_length=1, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estudia',
            field=models.BooleanField(choices=[(True, 'si'), (False, 'no')], default=(False, 'no')),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombres',
            field=models.CharField(max_length=90, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(90), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Nombres del Empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sexo',
            field=models.CharField(choices=[('f', 'Femenino'), ('m', 'Masculino')], max_length=1, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(20), helpers.validForm.PhoneNumberValidator()], verbose_name='Teléfono del Empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='tipo_sangre',
            field=models.CharField(choices=[('a+', 'A+ (Rh positivo)'), ('a-', 'A- (Rh negativo)'), ('b+', 'B+ (Rh positivo)'), ('b-', 'B- (Rh negativo)'), ('ab+', 'AB+ (Rh positivo)'), ('ab-', 'AB- (Rh negativo)'), ('o+', 'O+ (Rh positivo)'), ('o-', 'O- (Rh negativo)')], max_length=3, verbose_name='Tipo de Sangre'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='cedula',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(14), helpers.validForm.CedulaVenezolanaValidator()], verbose_name='Cédula de Identidad'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='sexo',
            field=models.CharField(choices=[('f', 'Femenino'), ('m', 'Masculino')], max_length=1, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='tipo_hijo',
            field=models.CharField(blank=True, choices=[('menor_12', 'Hijo menor de 12'), ('hijos_13_18', 'Hijo entre 13 y 18'), ('mayor_18', 'Hijo mayor de 18')], max_length=11, null=True, verbose_name='Tipo de Hijo'),
        ),
    ]
