# Generated by Django 5.1.1 on 2025-04-20 21:44

import django.core.validators
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Normativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=6, verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_by', models.CharField(max_length=6, verbose_name='Actualizado por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_by', models.CharField(blank=True, max_length=6, null=True, verbose_name='Eliminado por')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('name', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Nombre de Normativa')),
                ('file', models.FileField(upload_to='normativas/', verbose_name='Archivo')),
                ('date', models.DateField(blank=True, verbose_name='Fecha')),
                ('progre', models.CharField(choices=[('0', '0%'), ('10', '10%'), ('20', '20%'), ('30', '30%'), ('40', '40%'), ('50', '50%'), ('60', '60%'), ('70', '70%'), ('80', '80%'), ('90', '90%'), ('100', '100%')], default='0', max_length=3, verbose_name='Progreso:')),
                ('estado', models.CharField(choices=[('bor', 'Borrador'), ('rev', 'Revision'), ('pub', 'Publicado')], default='bor', max_length=3)),
            ],
            options={
                'verbose_name': 'normativa',
                'verbose_name_plural': 'normativas',
                'permissions': [('listar_normativa', 'Puede listar normativas'), ('agregar_normativa', 'Puede agregar normativa'), ('ver_normativa', 'Puede ver normativa'), ('editar_normativa', 'Puede actualizar normativa'), ('eliminar_normativa', 'Puede eliminar normativa')],
            },
        ),
        migrations.CreateModel(
            name='Reglamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=6, verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_by', models.CharField(max_length=6, verbose_name='Actualizado por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_by', models.CharField(blank=True, max_length=6, null=True, verbose_name='Eliminado por')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('name', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Nombre de Reglamento:')),
                ('file', models.FileField(upload_to='reglamentos/', verbose_name='Archivo')),
                ('date', models.DateField(blank=True, verbose_name='Fecha')),
                ('progre', models.CharField(choices=[('0', '0%'), ('10', '10%'), ('20', '20%'), ('30', '30%'), ('40', '40%'), ('50', '50%'), ('60', '60%'), ('70', '70%'), ('80', '80%'), ('90', '90%'), ('100', '100%')], max_length=64, verbose_name='Progreso:')),
                ('estado', models.CharField(choices=[('bor', 'Borrador'), ('rev', 'Revision'), ('pub', 'Publicado')], default='bor', max_length=3)),
            ],
            options={
                'verbose_name': 'reglamento',
                'verbose_name_plural': 'reglamentos',
                'permissions': [('listar_reglamento', 'Puede listar reglamentos'), ('agregar_reglamento', 'Puede agregar reglamento'), ('ver_reglamento', 'Puede ver reglamento'), ('editar_reglamento', 'Puede actualizar reglamento'), ('eliminar_reglamento', 'Puede eliminar reglamento')],
            },
        ),
    ]
