# Generated by Django 5.1.1 on 2025-03-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normativa',
            name='estado',
            field=models.CharField(choices=[('bor', 'Borrador'), ('rev', 'Revision'), ('pub', 'Publicado')], default='bor', max_length=3),
        ),
        migrations.AlterField(
            model_name='reglamento',
            name='estado',
            field=models.CharField(choices=[('bor', 'Borrador'), ('rev', 'Revision'), ('pub', 'Publicado')], default='bor', max_length=3),
        ),
    ]
