# Generated by Django 5.1.1 on 2025-01-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normativa',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='inactivo', max_length=8),
        ),
        migrations.AlterField(
            model_name='reglamento',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='inactivo', max_length=8),
        ),
    ]
