# Generated by Django 5.1.1 on 2025-01-17 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizacion", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="normativa",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="reglamento",
            name="estado",
        ),
    ]
