# Generated by Django 5.1.1 on 2025-05-10 22:06

import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normativa',
            name='file',
            field=models.FileField(upload_to='normativas/', validators=[helpers.validForm.Validate_pdf], verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='reglamento',
            name='file',
            field=models.FileField(upload_to='reglamentos/', validators=[helpers.validForm.Validate_pdf], verbose_name='Archivo'),
        ),
    ]
