# Generated by Django 5.1.1 on 2025-05-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0002_alter_normativa_file_alter_reglamento_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normativa',
            name='estado',
            field=models.CharField(choices=[('bor', 'Borrador'), ('rev', 'Revision'), ('pub', 'Publicado')], default='bor', max_length=3, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='reglamento',
            name='estado',
            field=models.CharField(choices=[('bor', 'Borrador'), ('rev', 'Revision'), ('pub', 'Publicado')], default='bor', max_length=3, verbose_name='Estatus'),
        ),
    ]
