# Generated by Django 5.1.1 on 2025-03-29 18:44

import django.core.validators
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0002_alter_normativa_estado_alter_reglamento_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normativa',
            name='name',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Nombre de Normativa'),
        ),
        migrations.AlterField(
            model_name='reglamento',
            name='name',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Nombre de Reglamento:'),
        ),
    ]
