# Generated by Django 5.1.1 on 2025-03-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0002_alter_normativa_estado_alter_reglamento_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='normativa',
            options={'permissions': [('listar_normativa', 'Puede listar normativas'), ('agregar_normativa', 'Puede agregar normativa'), ('ver_normativa', 'Puede ver normativa'), ('editar_normativa', 'Puede actualizar normativa'), ('eliminar_normativa', 'Puede eliminar normativa')], 'verbose_name': 'normativa', 'verbose_name_plural': 'normativas'},
        ),
        migrations.AlterModelOptions(
            name='reglamento',
            options={'permissions': [('listar_reglamento', 'Puede listar reglamentos'), ('agregar_reglamento', 'Puede agregar reglamento'), ('ver_reglamento', 'Puede ver reglamento'), ('editar_reglamento', 'Puede actualizar reglamento'), ('eliminar_reglamento', 'Puede eliminar reglamento')], 'verbose_name': 'reglamento', 'verbose_name_plural': 'reglamentos'},
        ),
        migrations.RemoveField(
            model_name='normativa',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reglamento',
            name='user',
        ),
        migrations.AlterField(
            model_name='reglamento',
            name='file',
            field=models.FileField(upload_to='reglamentos/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='reglamento',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nombre de Reglamento:'),
        ),
        migrations.AlterField(
            model_name='reglamento',
            name='progre',
            field=models.CharField(default='0', max_length=64, verbose_name='Progreso:'),
        ),
    ]
