from gestion_comunicacional.equipments.entities.EquipmentEntity import EquipmentEntity
from gestion_comunicacional.equipments.entities.EquipmentLoanEntity import EquipmentLoanEntity
from gestion_comunicacional.social_activity.entities.SocialActivityEntity import SocialActivityEntity
from gestion_comunicacional.social_media.entities.SocialMediaAccountEntity import SocialMediaAccountEntity
from gestion_comunicacional.social_media.entities.SocialMediaPostEntity import SocialMediaPostEntity

from django.contrib import admin

admin.site.register(SocialMediaAccountEntity)
admin.site.register(SocialMediaPostEntity)
admin.site.register(SocialActivityEntity)
admin.site.register(EquipmentEntity)
admin.site.register(EquipmentLoanEntity)
