# Generated by Django 5.1.1 on 2025-04-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'si'), (False, 'no')], default=(False, 'no')),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(choices=[(True, 'si'), (False, 'no')], default=(False, 'no')),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(choices=[(True, 'si'), (False, 'no')], default=(False, 'no')),
        ),
    ]
