# Generated by Django 5.0.3 on 2024-04-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrep', models.CharField(default='', max_length=64, verbose_name='Nombre del Proyecto:')),
                ('fechai', models.DateField(verbose_name='Fecha de Inicio')),
                ('fechac', models.DateField(verbose_name='Fecha de Culminación')),
                ('situacionp', models.CharField(default='', max_length=64, verbose_name='Situación Presupuestaria:')),
                ('montoproyecto', models.CharField(default='', max_length=64, verbose_name='Monto Total del Proyecto:')),
                ('responsableg', models.CharField(default='', max_length=64, verbose_name='Responsable Gerente:')),
                ('responsablet', models.CharField(default='', max_length=64, verbose_name='Responsable Técnico:')),
                ('responsabler', models.CharField(default='', max_length=64, verbose_name='Responsable Registrador:')),
                ('responsablea', models.CharField(default='', max_length=64, verbose_name='Responsable Administrativo:')),
                ('estatus', models.CharField(default='', max_length=64, verbose_name='Estatus del Proyecto:')),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombredir', models.CharField(default='', max_length=64, verbose_name='Nombre de la dirección:')),
                ('presuasig', models.CharField(default='', max_length=64, verbose_name='Presupuesto asignado:')),
                ('objeanual', models.CharField(default='', max_length=64, verbose_name='Objetivo general anual:')),
                ('numpartida', models.CharField(default='', max_length=10, verbose_name='Número de partida:')),
            ],
        ),
        migrations.CreateModel(
            name='Cedente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idc', models.CharField(default='', max_length=100, verbose_name='Id Cedente:')),
                ('partidac', models.CharField(default='', max_length=64, verbose_name='Partida')),
                ('generalc', models.CharField(default='', max_length=64, verbose_name='General')),
                ('espefc', models.CharField(default='', max_length=64, verbose_name='Específicaciones')),
                ('subespefc', models.CharField(default='', max_length=64, verbose_name='Sub-Especialidad')),
                ('denomc', models.CharField(default='', max_length=64, verbose_name='Denomincación')),
                ('presuacorc', models.CharField(default='', max_length=64, verbose_name='Presupuesto acordado')),
                ('caufechac', models.CharField(default='', max_length=64, verbose_name='Causado a la fecha')),
                ('dispc', models.CharField(default='', max_length=64, verbose_name='Disponible a causar')),
                ('montocc', models.CharField(default='', max_length=64, verbose_name='Monto a ceder')),
                ('saldofc', models.CharField(default='', max_length=64, verbose_name='Saldo final')),
                ('direccionc', models.CharField(default='', max_length=64, verbose_name='Dirección cedente')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrep', models.CharField(default='', max_length=64, verbose_name='Nombre del Proyecto:')),
                ('fechai', models.DateField(verbose_name='Fecha de Inicio')),
                ('fechac', models.DateField(verbose_name='Fecha de Culminación')),
                ('situacionp', models.CharField(default='', max_length=64, verbose_name='Situación Presupuestaria:')),
                ('montoproyecto', models.CharField(default='', max_length=64, verbose_name='Monto Total del Proyecto:')),
                ('responsableg', models.CharField(default='', max_length=64, verbose_name='Responsable Gerente:')),
                ('responsablet', models.CharField(default='', max_length=64, verbose_name='Responsable Técnico:')),
                ('responsabler', models.CharField(default='', max_length=64, verbose_name='Responsable Registrador:')),
                ('responsablea', models.CharField(default='', max_length=64, verbose_name='Responsable Administrativo:')),
                ('estatus', models.CharField(default='', max_length=64, verbose_name='Estatus del Proyecto:')),
            ],
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idr', models.CharField(default='', max_length=100, verbose_name='Id Receptor:')),
                ('partidar', models.CharField(default='', max_length=64, verbose_name='Partida')),
                ('generalr', models.CharField(default='', max_length=64, verbose_name='General')),
                ('espefr', models.CharField(default='', max_length=64, verbose_name='Específicaciones')),
                ('subespefr', models.CharField(default='', max_length=64, verbose_name='Sub-Especialidad')),
                ('denomr', models.CharField(default='', max_length=64, verbose_name='Denomincación')),
                ('presuacorr', models.CharField(default='', max_length=64, verbose_name='Presupuesto acordado')),
                ('caufechar', models.CharField(default='', max_length=64, verbose_name='Causado a la fecha')),
                ('dispr', models.CharField(default='', max_length=64, verbose_name='Disponible a causar')),
                ('montocr', models.CharField(default='', max_length=64, verbose_name='Monto a ceder')),
                ('saldofr', models.CharField(default='', max_length=64, verbose_name='Saldo final')),
                ('direccionr', models.CharField(default='', max_length=64, verbose_name='Dirección cedente')),
            ],
        ),
    ]
