# Generated by Django 5.0.3 on 2024-04-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechai', models.DateField(verbose_name='Fecha de Inicio')),
                ('fechaf', models.DateField(verbose_name='Fecha Final')),
                ('objetiv', models.CharField(default='', max_length=64, verbose_name='Objetivos:')),
                ('meta', models.CharField(default='', max_length=64, verbose_name='Meta:')),
            ],
        ),
        migrations.CreateModel(
            name='Objetivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechai', models.DateField(verbose_name='Fecha de Inicio')),
                ('fechaf', models.DateField(verbose_name='Fecha Final')),
                ('objetiv', models.CharField(default='', max_length=64, verbose_name='Objetivos:')),
                ('meta', models.CharField(default='', max_length=64, verbose_name='Meta:')),
            ],
        ),
    ]
