# Generated by Django 5.1.1 on 2024-11-23 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '__first__'),
        ('helpers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parroquia',
            name='id_cuadrante_paz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.cuadrantepaz'),
        ),
        migrations.DeleteModel(
            name='CuadrantePaz',
        ),
    ]
