# Generated by Django 5.1.1 on 2025-04-20 21:44

import django.core.validators
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrentePreventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=6, verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_by', models.CharField(max_length=6, verbose_name='Actualizado por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_by', models.CharField(blank=True, max_length=6, null=True, verbose_name='Eliminado por')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('donde_desarrollo', models.CharField(choices=[('Es', 'Escuela'), ('Pla', 'Plaza'), ('C', 'Calles'), ('Av', 'Avenida')], max_length=4)),
                ('personas_beneficiadas', models.TextField(blank=True, max_length=180, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(180), helpers.validForm.TextValidator()], verbose_name='Personas beneficiadas')),
                ('tipo_actividad', models.CharField(choices=[('Ed', 'Educativo'), ('D', 'Deportivo'), ('R', 'Recreativo'), ('C', 'Cultural'), ('A', 'Alimentación'), ('Sa', 'Salud'), ('AJS', 'Asesoria juridica y social'), ('Cur', 'Curso'), ('ta', 'Taller')], max_length=3)),
                ('fecha_realizo', models.DateField(verbose_name='Fecha de realización')),
                ('observaciones', models.TextField(blank=True, max_length=180, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(180), helpers.validForm.TextValidator()], verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Frente Preventivo',
                'verbose_name_plural': 'Frentes Preventivos',
                'permissions': [('listar_frentepreventivo', 'Puede listar frente preventivo'), ('agregar_frentepreventivo', 'Puede agregar frente preventivo'), ('ver_frentepreventivo', 'Puede ver frente preventivo'), ('editar_frentepreventivo', 'Puede actualizar frente preventivo'), ('eliminar_frentepreventivo', 'Puede eliminar frente preventivo')],
            },
        ),
        migrations.CreateModel(
            name='GestionComunicacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=6, verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_by', models.CharField(max_length=6, verbose_name='Actualizado por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_by', models.CharField(blank=True, max_length=6, null=True, verbose_name='Eliminado por')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('nombre_actividad', models.TextField(blank=True, max_length=180, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(180), helpers.validForm.TextValidator()], verbose_name='Nombre de la actividad')),
                ('actividad_realizada', models.TextField(blank=True, max_length=180, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(180), helpers.validForm.TextValidator()], verbose_name='Actividad Realizada')),
                ('descripcion_actividad', models.TextField(blank=True, max_length=180, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(180), helpers.validForm.TextValidator()], verbose_name='descripción actividad')),
                ('actividad_preventiva', models.CharField(choices=[('I', 'Individual'), ('Fp', 'Frente preventivo')], max_length=2)),
                ('estado', models.CharField(choices=[('1', 'Amazonas'), ('2', 'Anzoátegui'), ('3', 'Apure'), ('4', 'Aragua'), ('5', 'Barinas'), ('6', 'Bolívar'), ('7', 'Carabobo'), ('8', 'Cojedes'), ('9', 'Delta Amacuro'), ('10', 'Falcón'), ('11', 'Guárico'), ('12', 'Lara'), ('13', 'Mérida'), ('14', 'Miranda'), ('15', 'Monagas'), ('16', 'Nueva Esparta'), ('17', 'Portuguesa'), ('18', 'Sucre'), ('19', 'Táchira'), ('20', 'Trujillo'), ('21', 'Vargas'), ('22', 'Yaracuy'), ('23', 'Zulia'), ('24', 'Distrito Capital')], max_length=2, verbose_name='Estado')),
                ('municipio', models.CharField(max_length=90, verbose_name='Municipio')),
                ('parroquia', models.CharField(max_length=90, verbose_name='Parroquia')),
                ('estrategias_metodologicas', models.CharField(choices=[('AT', 'Acompañamineto tecnico'), ('S', 'Supervición'), ('C', 'Capacitacion')], max_length=2)),
                ('ambito_accion', models.CharField(choices=[('Ed', 'Educativo'), ('D', 'Deportivo'), ('R', 'Recreativo'), ('C', 'Cultural'), ('A', 'Alimentación'), ('Sa', 'Salud'), ('AJS', 'Asesoria juridica y social')], max_length=3, verbose_name='Ambito de acción')),
                ('poblacion_abordada', models.TextField(blank=True, max_length=180, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(180), helpers.validForm.TextValidator()], verbose_name='población abordada')),
                ('equipo_social', models.TextField(blank=True, max_length=180, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(180), helpers.validForm.TextValidator()], verbose_name='equipo social')),
                ('realizado_por', models.TextField(blank=True, max_length=180, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(180), helpers.validForm.TextValidator()], verbose_name='Realizado por')),
                ('validado_por', models.TextField(blank=True, max_length=180, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(180), helpers.validForm.TextValidator()], verbose_name='Validado por')),
                ('cedula', models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(14), helpers.validForm.CedulaVenezolanaValidator()], verbose_name='Cédula de identidad')),
                ('observaciones', models.TextField(blank=True, max_length=180, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(180), helpers.validForm.TextValidator()], verbose_name='Observaciones')),
                ('municipio_priorizado', models.BooleanField(choices=[(True, 'si'), (False, 'no')], default=(False, 'no'), verbose_name='Municipio priorizado')),
            ],
            options={
                'verbose_name': 'Gestion Comunicacional',
                'verbose_name_plural': 'Gestiones Comunicacionales',
                'permissions': [('listar_gestion_comunicacional', 'Puede listar gestion comunicacional'), ('agregar_gestion_comunicacional', 'Puede agregar gestion comunicacional'), ('ver_gestion_comunicacional', 'Puede ver gestion comunicacional'), ('editar_gestion_comunicacional', 'Puede actualizar gestion comunicacional'), ('eliminar_gestion_comunicacional', 'Puede eliminar gestion comunicacional')],
            },
        ),
    ]
