# Generated by Django 5.1.1 on 2025-05-10 20:28

import django.core.validators
import django.db.models.deletion
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptor',
            name='cedente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptores', to='presupuesto.cedente'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='numero_partida',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(10), helpers.validForm.TextValidator(extra_chars='-')], verbose_name='Número de partida presupuestaria'),
        ),
        migrations.AlterField(
            model_name='cedente',
            name='denomc',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4), helpers.validForm.TextValidator()], verbose_name='Denominación'),
        ),
        migrations.AlterField(
            model_name='cedente',
            name='direccionc',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4), helpers.validForm.TextValidator()], verbose_name='Dirección cedente'),
        ),
        migrations.AlterField(
            model_name='cedente',
            name='espefc',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Específicaciones'),
        ),
        migrations.AlterField(
            model_name='cedente',
            name='generalc',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='General'),
        ),
        migrations.AlterField(
            model_name='cedente',
            name='idc',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(4), helpers.validForm.TextValidator(extra_chars='-')], verbose_name='Identificador Cedente:'),
        ),
        migrations.AlterField(
            model_name='cedente',
            name='partidac',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4), helpers.validForm.TextValidator(extra_chars='-')], verbose_name='Partida Contable'),
        ),
        migrations.AlterField(
            model_name='cedente',
            name='subespefc',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Sub-Especialidad'),
        ),
    ]
