# Generated by Django 5.1.1 on 2025-04-17 20:49

import django.core.validators
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cedente',
            name='espefc',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Específicaciones'),
        ),
        migrations.AlterField(
            model_name='cedente',
            name='generalc',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(255)], verbose_name='General'),
        ),
        migrations.AlterField(
            model_name='cedente',
            name='idc',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(255), helpers.validForm.TextValidator(extra_chars='-')], verbose_name='Identificador Cedente:'),
        ),
        migrations.AlterField(
            model_name='cedente',
            name='partidac',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(255), helpers.validForm.TextValidator(extra_chars='-')], verbose_name='Partida Contable'),
        ),
        migrations.AlterField(
            model_name='cedente',
            name='presuacorc',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(0)], verbose_name='Presupuesto asignado'),
        ),
        migrations.AlterField(
            model_name='cedente',
            name='subespefc',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Sub-Especialidad'),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='espefr',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(64)], verbose_name='Específicaciones'),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='generalr',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(64)], verbose_name='General'),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='idr',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(100), helpers.validForm.TextValidator()], verbose_name='Identificador Receptor'),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='partidar',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Partida Contable'),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='subespefr',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(64)], verbose_name='Sub-Especialidad'),
        ),
    ]
