# Generated by Django 5.1.1 on 2025-03-22 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accion',
            options={'permissions': [('listar_accion', 'Puede listar acciones'), ('agregar_accion', 'Puede agregar accion'), ('ver_accion', 'Puede ver accion'), ('editar_accion', 'Puede actualizar accion'), ('eliminar_accion', 'Puede eliminar accion'), ('pdf_accion', 'Puede generar pdf de accion')], 'verbose_name': 'Accion', 'verbose_name_plural': 'Acciones'},
        ),
        migrations.AlterModelOptions(
            name='asignacion',
            options={'permissions': [('listar_asignacion', 'Puede listar asignacion'), ('agregar_asignacion', 'Puede agregar asignacion'), ('ver_asignacion', 'Puede ver asignacion'), ('editar_asignacion', 'Puede actualizar asignacion'), ('eliminar_asignacion', 'Puede eliminar asignacion'), ('pdf_asignacion', 'Puede generar pdf de asignacion')], 'verbose_name': 'Asignacion', 'verbose_name_plural': 'Asignaciones'},
        ),
        migrations.AlterModelOptions(
            name='cedente',
            options={'permissions': [('listar_cedente', 'Puede listar cedente'), ('agregar_cedente', 'Puede agregar cedente'), ('ver_cedente', 'Puede ver cedente'), ('editar_cedente', 'Puede actualizar cedente'), ('eliminar_cedente', 'Puede eliminar cedente'), ('pdf_cedente', 'Puede generar pdf de cedente')], 'verbose_name': 'Cedente', 'verbose_name_plural': 'Cedentes'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': [('listar_proyecto', 'Puede listar proyectos'), ('agregar_proyecto', 'Puede agregar proyecto'), ('ver_proyecto', 'Puede ver proyecto'), ('editar_proyecto', 'Puede actualizar proyecto'), ('eliminar_proyecto', 'Puede eliminar proyecto'), ('pdf_proyecto', 'Puede generar pdf de proyecto')], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='receptor',
            options={'permissions': [('listar_receptor', 'Puede listar receptor'), ('agregar_receptor', 'Puede agregar receptor'), ('ver_receptor', 'Puede ver receptor'), ('editar_receptor', 'Puede actualizar receptor'), ('eliminar_receptor', 'Puede eliminar receptor'), ('pdf_receptor', 'Puede generar pdf de receptor')], 'verbose_name': 'Receptor', 'verbose_name_plural': 'Receptores'},
        ),
    ]
