# Generated by Django 5.1.1 on 2025-04-07 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacion',
            options={'permissions': [('listar_asignar_presupuesto', 'Puede listar asignaciones'), ('agregar_asignar_presupuesto', 'Puede agregar asignacion'), ('ver_asignar_presupuesto', 'Puede ver asignacion'), ('editar_asignar_presupuesto', 'Puede actualizar asignacion'), ('eliminar_asignar_presupuesto', 'Puede eliminar asignacion'), ('pdf_asignar_presupuesto', 'Puede generar pdf de asignacion')], 'verbose_name': 'Asignacion', 'verbose_name_plural': 'Asignaciones'},
        ),
    ]
