# Generated by Django 5.1.1 on 2025-03-29 18:44

import django.core.validators
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0002_alter_accion_options_alter_asignacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accion',
            name='estatus',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Estatus del Proyecto:'),
        ),
        migrations.AlterField(
            model_name='accion',
            name='monto',
            field=models.CharField(max_length=64, verbose_name='Monto asignado:'),
        ),
        migrations.AlterField(
            model_name='accion',
            name='responsable_administrativo',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Responsable Administrativo:'),
        ),
        migrations.AlterField(
            model_name='accion',
            name='responsable_gerente',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Responsable Gerente:'),
        ),
        migrations.AlterField(
            model_name='accion',
            name='responsable_registrador',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Responsable Registrador:'),
        ),
        migrations.AlterField(
            model_name='accion',
            name='responsable_tecnico',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Responsable Técnico:'),
        ),
        migrations.AlterField(
            model_name='accion',
            name='situacion_presupuestaria',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(64), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Situación Presupuestaria:'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='departamento',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Nombre de la dirección'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='numero_partida',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(10), helpers.validForm.UnicodeAlphaSpaceValidator(extra_chars='-')], verbose_name='Número de partida presupuestaria'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='objetivo',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Objetivo general anual'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='presupuesto',
            field=models.CharField(max_length=64, verbose_name='Presupuesto asignado'),
        ),
        migrations.AlterField(
            model_name='cedente',
            name='denomc',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(255), helpers.validForm.TextValidator()], verbose_name='Denominación'),
        ),
        migrations.AlterField(
            model_name='cedente',
            name='direccionc',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(255), helpers.validForm.TextValidator()], verbose_name='Dirección cedente'),
        ),
        migrations.AlterField(
            model_name='cedente',
            name='espefc',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxLengthValidator(255), helpers.validForm.PositiveIntegerValidator()], verbose_name='Específicaciones'),
        ),
        migrations.AlterField(
            model_name='cedente',
            name='generalc',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxLengthValidator(255), helpers.validForm.PositiveIntegerValidator()], verbose_name='General'),
        ),
        migrations.AlterField(
            model_name='cedente',
            name='idc',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(255), helpers.validForm.UnicodeAlphaSpaceValidator(extra_chars='-')], verbose_name='Identificador Cedente:'),
        ),
        migrations.AlterField(
            model_name='cedente',
            name='montocc',
            field=models.CharField(max_length=64, verbose_name='Monto comprometido'),
        ),
        migrations.AlterField(
            model_name='cedente',
            name='partidac',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(255), helpers.validForm.UnicodeAlphaSpaceValidator(extra_chars='-')], verbose_name='Partida Contable'),
        ),
        migrations.AlterField(
            model_name='cedente',
            name='presuacorc',
            field=models.CharField(max_length=64, verbose_name='Presupuesto asignado'),
        ),
        migrations.AlterField(
            model_name='cedente',
            name='subespefc',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxLengthValidator(255), helpers.validForm.PositiveIntegerValidator()], verbose_name='Sub-Especialidad'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estatus',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Estatus del Proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='montoproyecto',
            field=models.CharField(max_length=64, verbose_name='Monto Total del Proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombrep',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Nombre del Proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='responsablea',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(64), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Responsable Administrativo'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='responsableg',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(64), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Responsable Gerente'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='responsabler',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(64), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Responsable Registrador'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='responsablet',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(64), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Responsable Técnico'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='situacionp',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(64), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Situación Presupuestaria'),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='caufechar',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Causado a la fecha'),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='denomr',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Denomincación'),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='direccionr',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Dirección cedente'),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='dispr',
            field=models.CharField(max_length=64, verbose_name='Disponible a causar'),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='espefr',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(64), helpers.validForm.PositiveIntegerValidator()], verbose_name='Específicaciones'),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='generalr',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(64), helpers.validForm.PositiveIntegerValidator()], verbose_name='General'),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='idr',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(100), helpers.validForm.UnicodeAlphaSpaceValidator(extra_chars='-')], verbose_name='Identificador Receptor'),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='montocr',
            field=models.CharField(max_length=64, verbose_name='Monto a ceder'),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='partidar',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(64), helpers.validForm.UnicodeAlphaSpaceValidator(extra_chars='-')], verbose_name='Partida Contable'),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='presuacorr',
            field=models.CharField(max_length=64, verbose_name='Presupuesto acordado'),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='saldofr',
            field=models.CharField(max_length=64, verbose_name='Saldo final'),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='subespefr',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(64), helpers.validForm.PositiveIntegerValidator()], verbose_name='Sub-Especialidad'),
        ),
    ]
