# Generated by Django 5.1.1 on 2025-05-10 22:06

import django.core.validators
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0002_receptor_cedente_alter_asignacion_numero_partida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traspaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=6, verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_by', models.CharField(max_length=6, verbose_name='Actualizado por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_by', models.CharField(blank=True, max_length=6, null=True, verbose_name='Eliminado por')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('proyecto_acciones', models.CharField(choices=[('proyecto', 'Proyecto'), ('accion', 'Acción')], max_length=64, validators=[django.core.validators.MinLengthValidator(3), helpers.validForm.TextValidator()], verbose_name='Proyecto o Acción')),
            ],
            options={
                'verbose_name': 'Traspaso',
                'verbose_name_plural': 'Traspasos',
                'permissions': [('listar_traspaso', 'Puede listar traspaso'), ('agregar_traspaso', 'Puede agregar traspaso'), ('ver_traspaso', 'Puede ver traspaso'), ('editar_traspaso', 'Puede actualizar traspaso'), ('eliminar_traspaso', 'Puede eliminar traspaso'), ('exel_traspaso', 'Puede generar pdf de traspaso')],
            },
        ),
    ]
