# Generated by Django 5.1.1 on 2025-05-10 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0003_traspaso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptor',
            name='cedente',
        ),
        migrations.AddField(
            model_name='cedente',
            name='traspaso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cedentes', to='presupuesto.traspaso'),
        ),
        migrations.AddField(
            model_name='receptor',
            name='traspaso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptores', to='presupuesto.traspaso'),
        ),
    ]
