# Generated by Django 5.1.1 on 2025-05-13 20:34

import django.core.validators
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0004_remove_receptor_cedente_cedente_traspaso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accion',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='accion',
            name='proyecto_acciones',
            field=models.CharField(choices=[('proyecto', 'Proyecto'), ('accion', 'Acciones Centralizadas')], max_length=64, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Proyecto o Acciones Centralizadas'),
        ),
        migrations.AlterField(
            model_name='traspaso',
            name='proyecto_acciones',
            field=models.CharField(choices=[('proyecto', 'Proyecto'), ('accion', 'Acciones Centralizadas')], max_length=64, validators=[django.core.validators.MinLengthValidator(3), helpers.validForm.TextValidator()], verbose_name='Proyecto o Acciones Centralizadas'),
        ),
    ]
