# Generated by Django 5.1.1 on 2025-05-13 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0005_remove_accion_proyecto_accion_proyecto_acciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accion',
            name='estatus',
        ),
    ]
