# Generated by Django 5.1.1 on 2025-05-14 22:02

import django.core.validators
import django.db.models.deletion
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0006_remove_accion_estatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cedente',
            name='traspaso',
        ),
        migrations.RemoveField(
            model_name='receptor',
            name='traspaso',
        ),
        migrations.AddField(
            model_name='receptor',
            name='cedente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cedente', to='presupuesto.cedente'),
        ),
        migrations.AlterField(
            model_name='cedente',
            name='idc',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4), helpers.validForm.TextValidator(extra_chars='-')], verbose_name='Identificador Cedente:'),
        ),
        migrations.DeleteModel(
            name='Traspaso',
        ),
    ]
