# Generated by Django 5.1.1 on 2025-05-21 23:25

import django.core.validators
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0007_remove_cedente_traspaso_remove_receptor_traspaso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=6, verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_by', models.CharField(max_length=6, verbose_name='Actualizado por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_by', models.CharField(blank=True, max_length=6, null=True, verbose_name='Eliminado por')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('codigo', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(64), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Código:')),
                ('titulo', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Título:')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'permissions': [('listar_partida', 'Puede listar partida'), ('agregar_partida', 'Puede agregar partida'), ('ver_accion', 'Puede ver partida'), ('editar_partida', 'Puede actualizar partida'), ('eliminar_partida', 'Puede eliminar partida'), ('pdf_partida', 'Puede generar pdf de accion')],
            },
        ),
        migrations.AlterField(
            model_name='cedente',
            name='montocc',
            field=models.CharField(max_length=64, validators=[helpers.validForm.CurrencyValidator()], verbose_name='Monto comprometido'),
        ),
        migrations.AlterField(
            model_name='cedente',
            name='presuacorc',
            field=models.CharField(max_length=64, validators=[helpers.validForm.CurrencyValidator()], verbose_name='Presupuesto asignado'),
        ),
        migrations.AlterField(
            model_name='cedente',
            name='saldofc',
            field=models.CharField(max_length=64, validators=[helpers.validForm.CurrencyValidator()], verbose_name='Saldo final'),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='dispr',
            field=models.CharField(max_length=64, validators=[helpers.validForm.CurrencyValidator()], verbose_name='Disponible a causar'),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='montocr',
            field=models.CharField(max_length=64, validators=[helpers.validForm.CurrencyValidator()], verbose_name='Monto a ceder'),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='presuacorr',
            field=models.CharField(max_length=64, validators=[helpers.validForm.CurrencyValidator()], verbose_name='Presupuesto acordado'),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='saldofr',
            field=models.CharField(max_length=64, validators=[helpers.validForm.CurrencyValidator()], verbose_name='Saldo final'),
        ),
    ]
