# Generated by Django 5.1.1 on 2025-05-24 17:45

import django.core.validators
import django.db.models.deletion
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0008_partida_alter_cedente_montocc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cedente',
            name='partida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cedente', to='presupuesto.partida'),
        ),
        migrations.AddField(
            model_name='receptor',
            name='partida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptor', to='presupuesto.partida'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='codigo',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(64), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Código:'),
        ),
    ]
