# Generated by Django 5.1.1 on 2025-05-24 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0009_cedente_partida_receptor_partida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptor',
            name='cedente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptores', to='presupuesto.cedente'),
        ),
    ]
