# Generated by Django 5.1.1 on 2025-05-24 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0011_alter_partida_codigo_alter_receptor_cedente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cedente',
            name='partida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='presupuesto.partida'),
        ),
    ]
