# Generated by Django 5.1.1 on 2025-05-24 21:25

import django.core.validators
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0012_alter_cedente_partida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='codigo',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(64), helpers.validForm.PartidaCodeValidator()], verbose_name='Código:'),
        ),
    ]
