# Generated by Django 5.1.1 on 2025-05-24 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0013_alter_partida_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cedente',
            name='espefc',
        ),
        migrations.RemoveField(
            model_name='cedente',
            name='generalc',
        ),
        migrations.RemoveField(
            model_name='cedente',
            name='idc',
        ),
        migrations.RemoveField(
            model_name='cedente',
            name='partidac',
        ),
        migrations.RemoveField(
            model_name='cedente',
            name='subespefc',
        ),
        migrations.RemoveField(
            model_name='receptor',
            name='espefr',
        ),
        migrations.RemoveField(
            model_name='receptor',
            name='generalr',
        ),
        migrations.RemoveField(
            model_name='receptor',
            name='idr',
        ),
        migrations.RemoveField(
            model_name='receptor',
            name='partidar',
        ),
        migrations.RemoveField(
            model_name='receptor',
            name='subespefr',
        ),
    ]
