# Generated by Django 5.1.1 on 2025-05-27 03:19

import django.core.validators
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0014_remove_cedente_espefc_remove_cedente_generalc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptor',
            name='direccionr',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Dirección receptor'),
        ),
    ]
