# Generated by Django 5.1.1 on 2025-05-29 16:38

import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0015_alter_receptor_direccionr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accion',
            name='monto',
            field=models.CharField(max_length=64, validators=[helpers.validForm.CurrencyValidator()], verbose_name='Monto asignado:'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='presupuesto',
            field=models.CharField(max_length=64, validators=[helpers.validForm.CurrencyValidator()], verbose_name='Presupuesto asignado'),
        ),
    ]
