# Generated by Django 5.0.3 on 2024-04-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(max_length=30)),
                ('Sede', models.CharField(max_length=30)),
                ('Departamento', models.CharField(max_length=30)),
                ('Tipoincidencia', models.CharField(max_length=30)),
                ('Usuario', models.CharField(max_length=30)),
                ('Observaciones', models.CharField(max_length=100)),
            ],
        ),
    ]
