# Generated by Django 5.1.1 on 2025-04-20 21:44

import django.core.validators
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=6, verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_by', models.CharField(max_length=6, verbose_name='Actualizado por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_by', models.CharField(blank=True, max_length=6, null=True, verbose_name='Eliminado por')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('name', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(64), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(64), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Apellido')),
                ('cedula', models.CharField(max_length=64, verbose_name='Cédula')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(20), helpers.validForm.PhoneNumberValidator()], verbose_name='Teléfono')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('direccion', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Dirección')),
                ('cargo', models.CharField(max_length=64, verbose_name='Cargo')),
                ('hora', models.CharField(max_length=64, verbose_name='Hora de Entrada')),
            ],
            options={
                'verbose_name': 'entrada',
                'verbose_name_plural': 'entradas',
                'permissions': [('listar_entradas', 'Listar entradas'), ('agregar_entrada', 'Agregar entrada'), ('ver_entrada', 'Ver entrada'), ('modificar_entrada', 'Modificar entrada'), ('eliminar_entrada', 'Eliminar entrada')],
            },
        ),
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=6, verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_by', models.CharField(max_length=6, verbose_name='Actualizado por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_by', models.CharField(blank=True, max_length=6, null=True, verbose_name='Eliminado por')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('name', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(255), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(255), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Apellido')),
                ('cedula', models.CharField(max_length=64, verbose_name='Cédula')),
                ('tipo', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(255), helpers.validForm.TextValidator()], verbose_name='Tipo de Gestión')),
                ('descripcion', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(255), helpers.validForm.TextValidator()], verbose_name='Descripción')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('direccion', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(255), helpers.validForm.TextValidator()], verbose_name='Dirección')),
                ('cargo', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(255), helpers.validForm.TextValidator()], verbose_name='Cargo')),
                ('hora', models.CharField(max_length=64, verbose_name='Hora de Entrada')),
            ],
            options={
                'verbose_name': 'gestion',
                'verbose_name_plural': 'gestiones',
                'permissions': [('listar_gestiones', 'Listar gestiones'), ('agregar_gestion', 'Agregar gestion'), ('ver_gestion', 'Ver gestion'), ('modificar_gestion', 'Modificar gestion'), ('eliminar_gestion', 'Eliminar gestion')],
            },
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=6, verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_by', models.CharField(max_length=6, verbose_name='Actualizado por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_by', models.CharField(blank=True, max_length=6, null=True, verbose_name='Eliminado por')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('name', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(255), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(255), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Apellido')),
                ('cedula', models.CharField(max_length=64, verbose_name='Cédula:')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(20), helpers.validForm.PhoneNumberValidator()], verbose_name='Teléfono:')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('direccion', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(255), helpers.validForm.TextValidator()], verbose_name='Dirección')),
                ('cargo', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(255), helpers.validForm.TextValidator()], verbose_name='Cargo')),
                ('hora', models.TimeField(verbose_name='Hora de Entrada')),
            ],
            options={
                'verbose_name': 'salida',
                'verbose_name_plural': 'salidas',
                'permissions': [('listar_salidas', 'Listar salidas'), ('agregar_salida', 'Agregar salida'), ('ver_salida', 'Ver salida'), ('modificar_salida', 'Modificar salida'), ('eliminar_salida', 'Eliminar salida')],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=6, verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_by', models.CharField(max_length=6, verbose_name='Actualizado por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_by', models.CharField(blank=True, max_length=6, null=True, verbose_name='Eliminado por')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('nombre', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(255), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(255), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Apellido')),
                ('cedula', models.CharField(max_length=64, verbose_name='Cédula de identidad')),
                ('modelo', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Modelo')),
                ('vehiculo', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Tipo de vehiculo')),
                ('motivo', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Motivo')),
                ('capagasolina', models.CharField(max_length=64, verbose_name='Capacidad de Gasolina')),
                ('cantigasolina', models.CharField(max_length=64, verbose_name='Cantidad de Gasolina')),
                ('placa', models.CharField(max_length=64, verbose_name='Placa')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.CharField(max_length=64, verbose_name='Hora')),
            ],
            options={
                'verbose_name': 'vehiculo',
                'verbose_name_plural': 'vehiculos',
                'permissions': [('listar_vehiculos', 'Listar vehiculos'), ('agregar_vehiculo', 'Agregar vehiculo'), ('ver_vehiculo', 'Ver vehiculo'), ('modificar_vehiculo', 'Modificar vehiculo'), ('eliminar_vehiculo', 'Eliminar vehiculo')],
            },
        ),
    ]
