# Generated by Django 5.1.1 on 2025-01-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='cantigasolina',
            field=models.CharField(default='', max_length=64, verbose_name='Cantidad de Gasolina:'),
        ),
    ]
