# Generated by Django 5.1.1 on 2025-04-06 23:22

import django.core.validators
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='apellido',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(64), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='direccion',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='name',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(64), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Nombre'),
        ),
    ]
