# Generated by Django 5.1.1 on 2025-03-22 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrada',
            options={'permissions': [('listar_entradas', 'Listar entradas'), ('agregar_entrada', 'Agregar entrada'), ('ver_entrada', 'Ver entrada'), ('modificar_entrada', 'Modificar entrada'), ('eliminar_entrada', 'Eliminar entrada')], 'verbose_name': 'entrada', 'verbose_name_plural': 'entradas'},
        ),
        migrations.AlterModelOptions(
            name='gestion',
            options={'permissions': [('listar_gestiones', 'Listar gestiones'), ('agregar_gestion', 'Agregar gestion'), ('ver_gestion', 'Ver gestion'), ('modificar_gestion', 'Modificar gestion'), ('eliminar_gestion', 'Eliminar gestion')], 'verbose_name': 'gestion', 'verbose_name_plural': 'gestiones'},
        ),
        migrations.AlterModelOptions(
            name='salida',
            options={'permissions': [('listar_salidas', 'Listar salidas'), ('agregar_salida', 'Agregar salida'), ('ver_salida', 'Ver salida'), ('modificar_salida', 'Modificar salida'), ('eliminar_salida', 'Eliminar salida')], 'verbose_name': 'salida', 'verbose_name_plural': 'salidas'},
        ),
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': [('listar_vehiculos', 'Listar vehiculos'), ('agregar_vehiculo', 'Agregar vehiculo'), ('ver_vehiculo', 'Ver vehiculo'), ('modificar_vehiculo', 'Modificar vehiculo'), ('eliminar_vehiculo', 'Eliminar vehiculo')], 'verbose_name': 'vehiculo', 'verbose_name_plural': 'vehiculos'},
        ),
    ]
