# Generated by Django 5.1.1 on 2025-04-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='hora',
            field=models.TimeField(verbose_name='Hora de Entrada'),
        ),
    ]
