# Generated by Django 5.1.1 on 2025-05-13 22:13

import django.core.validators
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='cedula',
            field=models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(14), helpers.validForm.CedulaVenezolanaValidator()], verbose_name='Cédula'),
        ),
    ]
