# Generated by Django 5.1.1 on 2025-03-29 18:45

import django.core.validators
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_alter_entrada_options_alter_gestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='apellido',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(64), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='cargo',
            field=models.CharField(max_length=64, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='cedula',
            field=models.CharField(max_length=64, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='direccion',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='hora',
            field=models.CharField(max_length=64, verbose_name='Hora de Entrada'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='name',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(64), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(20), helpers.validForm.PhoneNumberValidator()], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='apellido',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(255), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='cargo',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(255), helpers.validForm.TextValidator()], verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='cedula',
            field=models.CharField(max_length=64, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='descripcion',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(255), helpers.validForm.TextValidator()], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='direccion',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(255), helpers.validForm.TextValidator()], verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='hora',
            field=models.CharField(max_length=64, verbose_name='Hora de Entrada'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='name',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(255), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='tipo',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(255), helpers.validForm.TextValidator()], verbose_name='Tipo de Gestión'),
        ),
        migrations.AlterField(
            model_name='salida',
            name='apellido',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(255), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='salida',
            name='cargo',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(255), helpers.validForm.TextValidator()], verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='salida',
            name='cedula',
            field=models.CharField(max_length=64, verbose_name='Cédula:'),
        ),
        migrations.AlterField(
            model_name='salida',
            name='direccion',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(255), helpers.validForm.TextValidator()], verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='salida',
            name='hora',
            field=models.CharField(max_length=64, verbose_name='Hora de Entrada'),
        ),
        migrations.AlterField(
            model_name='salida',
            name='name',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(255), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='salida',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(20), helpers.validForm.PhoneNumberValidator()], verbose_name='Teléfono:'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='apellido',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(255), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='cantigasolina',
            field=models.CharField(max_length=64, verbose_name='Cantidad de Gasolina'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='capagasolina',
            field=models.CharField(max_length=64, verbose_name='Capacidad de Gasolina'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='cedula',
            field=models.CharField(max_length=64, verbose_name='Cédula de identidad'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='hora',
            field=models.CharField(max_length=64, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='motivo',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='nombre',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(255), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=64, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='vehiculo',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(64), helpers.validForm.TextValidator()], verbose_name='Tipo de vehiculo'),
        ),
    ]
