# Generated by Django 5.1.1 on 2025-04-20 21:44

import django.core.validators
import django.db.models.deletion
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=6, verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_by', models.CharField(max_length=6, verbose_name='Actualizado por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_by', models.CharField(blank=True, max_length=6, null=True, verbose_name='Eliminado por')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'permissions': [('listar_organismo_emergencia', 'Puede listar tipo organismo'), ('agregar_organismo_emergencia', 'Puede agregar tipo organismo'), ('ver_organismo_emergencia', 'Puede ver tipo organismo'), ('editar_organismo_emergencia', 'Puede actualizar tipo organismo'), ('eliminar_organismo_emergencia', 'Puede eliminar tipo organismo')],
            },
        ),
        migrations.CreateModel(
            name='TipoIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=6, verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_by', models.CharField(max_length=6, verbose_name='Actualizado por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_by', models.CharField(blank=True, max_length=6, null=True, verbose_name='Eliminado por')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('nombre_incidencia', models.CharField(max_length=120)),
            ],
            options={
                'permissions': [('listar_tipo_incidencia_emergencia', 'Puede listar tipo incidencia'), ('agregar_tipo_incidencia_emergencia', 'Puede agregar tipo incidencia'), ('ver_tipo_incidencia_emergencia', 'Puede ver tipo incidencia'), ('editar_tipo_incidencia_emergencia', 'Puede actualizar tipo incidencia'), ('eliminar_tipo_incidencia_emergencia', 'Puede eliminar tipo incidencia')],
            },
        ),
        migrations.CreateModel(
            name='Emergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=6, verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_by', models.CharField(max_length=6, verbose_name='Actualizado por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_by', models.CharField(blank=True, max_length=6, null=True, verbose_name='Eliminado por')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('denunciante', models.CharField(max_length=180, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(180), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Nombre del denunciante')),
                ('telefono_denunciante', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(20), helpers.validForm.PhoneNumberValidator()], verbose_name='Teléfono del denunciante')),
                ('estado', models.CharField(choices=[('1', 'Amazonas'), ('2', 'Anzoátegui'), ('3', 'Apure'), ('4', 'Aragua'), ('5', 'Barinas'), ('6', 'Bolívar'), ('7', 'Carabobo'), ('8', 'Cojedes'), ('9', 'Delta Amacuro'), ('10', 'Falcón'), ('11', 'Guárico'), ('12', 'Lara'), ('13', 'Mérida'), ('14', 'Miranda'), ('15', 'Monagas'), ('16', 'Nueva Esparta'), ('17', 'Portuguesa'), ('18', 'Sucre'), ('19', 'Táchira'), ('20', 'Trujillo'), ('21', 'Vargas'), ('22', 'Yaracuy'), ('23', 'Zulia'), ('24', 'Distrito Capital')], max_length=2, verbose_name='Estado')),
                ('municipio', models.CharField(max_length=90, verbose_name='Municipio')),
                ('parroquia', models.CharField(max_length=90, verbose_name='Parroquia')),
                ('direccion_incidencia', models.TextField(blank=True, max_length=180, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(180), helpers.validForm.TextValidator()], verbose_name='Dirección de la incidencia')),
                ('observaciones', models.TextField(blank=True, max_length=180, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(180), helpers.validForm.TextValidator()], verbose_name='Observaciones')),
                ('telefono_cuadrante_paz', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(20), helpers.validForm.PhoneNumberValidator()], verbose_name='Teléfono del Cuadrente de Paz')),
                ('organismo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergencia.organismo')),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergencia.tipoincidencia')),
            ],
            options={
                'verbose_name': 'emergencia',
                'verbose_name_plural': 'emergencias',
                'permissions': [('listar_emergencia', 'Puede listar emergencias'), ('agregar_emergencia', 'Puede agregar emergencia'), ('ver_emergencia', 'Puede ver emergencia'), ('editar_emergencia', 'Puede actualizar emergencia'), ('eliminar_emergencia', 'Puede eliminar emergencia')],
            },
        ),
    ]
