# Generated by Django 5.1.1 on 2025-04-06 23:22

import django.core.validators
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencia',
            name='direccion_incidencia',
            field=models.TextField(blank=True, max_length=180, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(180), helpers.validForm.TextValidator()], verbose_name='Dirección de la incidencia'),
        ),
        migrations.AlterField(
            model_name='emergencia',
            name='observaciones',
            field=models.TextField(blank=True, max_length=180, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(180), helpers.validForm.TextValidator()], verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='emergencia',
            name='telefono_cuadrante_paz',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(20), helpers.validForm.PhoneNumberValidator()], verbose_name='Teléfono del Cuadrente de Paz'),
        ),
        migrations.AlterField(
            model_name='emergencia',
            name='telefono_denunciante',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(20), helpers.validForm.PhoneNumberValidator()], verbose_name='Teléfono del denunciante'),
        ),
    ]
