# Generated by Django 5.1.1 on 2025-03-22 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencia',
            options={'permissions': [('listar_emergencia', 'Puede listar emergencias'), ('agregar_emergencia', 'Puede agregar emergencia'), ('ver_emergencia', 'Puede ver emergencia'), ('editar_emergencia', 'Puede actualizar emergencia'), ('eliminar_emergencia', 'Puede eliminar emergencia')], 'verbose_name': 'emergencia', 'verbose_name_plural': 'emergencias'},
        ),
    ]
