# Generated by Django 5.1.1 on 2025-03-29 18:44

import django.core.validators
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencia', '0002_alter_emergencia_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencia',
            name='denunciante',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(180), helpers.validForm.UnicodeAlphaSpaceValidator()], verbose_name='Nombre del denunciante'),
        ),
        migrations.AlterField(
            model_name='emergencia',
            name='direccion_incidencia',
            field=models.TextField(blank=True, max_length=180, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(180), helpers.validForm.TextValidator()], verbose_name='Direccion de la incidencia'),
        ),
        migrations.AlterField(
            model_name='emergencia',
            name='observaciones',
            field=models.TextField(blank=True, max_length=180, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(180), helpers.validForm.TextValidator()], verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='emergencia',
            name='telefono_cuadrante_paz',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(20), helpers.validForm.PhoneNumberValidator()], verbose_name='Telefono del Cuadrente de Paz'),
        ),
        migrations.AlterField(
            model_name='emergencia',
            name='telefono_denunciante',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(20), helpers.validForm.PhoneNumberValidator()], verbose_name='Telefono del denunciante'),
        ),
    ]
