# Generated by Django 5.1.1 on 2024-09-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(blank=True, max_length=50, null=True)),
                ('ente', models.CharField(blank=True, max_length=50, null=True)),
                ('nombres_d', models.CharField(max_length=50)),
                ('apellidos_d', models.CharField(max_length=50)),
                ('cedula_d', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion_d', models.CharField(max_length=150)),
                ('nombres_denunciado', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidos_denunciado', models.CharField(blank=True, max_length=50, null=True)),
                ('cedula_denunciado', models.CharField(blank=True, max_length=50, null=True)),
                ('motivo', models.CharField(max_length=400)),
                ('zona', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_denuncia', models.DateField()),
                ('fecha_incidente', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'denuncia',
                'verbose_name_plural': 'denuncias',
            },
        ),
    ]
