# Generated by Django 5.1.1 on 2025-04-20 21:44

import django.core.validators
import django.db.models.deletion
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denunciado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=6, verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_by', models.CharField(max_length=6, verbose_name='Actualizado por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_by', models.CharField(blank=True, max_length=6, null=True, verbose_name='Eliminado por')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('nombres', models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(120), helpers.validForm.TextValidator()], verbose_name='Nombre del denunciado')),
                ('apellidos', models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(120), helpers.validForm.TextValidator()], verbose_name='Apellido del denunciado')),
                ('cedula', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(14), helpers.validForm.CedulaVenezolanaValidator()], verbose_name='Cédula del denunciado')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(20), helpers.validForm.PhoneNumberValidator()], verbose_name='Teléfono del denunciado')),
                ('email', models.EmailField(blank=True, max_length=60, null=True, verbose_name='Correo electrónico del denunciado')),
                ('direccion', models.CharField(blank=True, max_length=180, null=True, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(180), helpers.validForm.TextValidator()], verbose_name='Dirección del denunciado')),
            ],
            options={
                'verbose_name': 'Denunciado',
                'verbose_name_plural': 'Denunciados',
                'permissions': [('listar_denunciado', 'Puede listar denunciados'), ('agregar_denunciado', 'Puede agregar denunciado'), ('ver_denunciado', 'Puede ver denunciado'), ('editar_denunciado', 'Puede actualizar denunciado'), ('eliminar_denunciado', 'Puede eliminar denunciado')],
            },
        ),
        migrations.CreateModel(
            name='Denunciante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=6, verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_by', models.CharField(max_length=6, verbose_name='Actualizado por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_by', models.CharField(blank=True, max_length=6, null=True, verbose_name='Eliminado por')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('nombres', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(120), helpers.validForm.TextValidator()], verbose_name='Nombre del denunciante')),
                ('apellidos', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(120), helpers.validForm.TextValidator()], verbose_name='Apellido del denunciante')),
                ('cedula', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(14), helpers.validForm.CedulaVenezolanaValidator()], verbose_name='Cédula del denunciante')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(20), helpers.validForm.PhoneNumberValidator()], verbose_name='Teléfono del denunciante')),
                ('email', models.EmailField(blank=True, max_length=60, null=True, verbose_name='Correo electrónico del denunciante')),
                ('direccion', models.CharField(max_length=180, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(180), helpers.validForm.TextValidator()], verbose_name='Dirección del denunciante')),
            ],
            options={
                'verbose_name': 'Denunciante',
                'verbose_name_plural': 'Denunciantes',
                'permissions': [('listar_denunciante', 'Puede listar denunciantes'), ('agregar_denunciante', 'Puede agregar denunciante'), ('ver_denunciante', 'Puede ver denunciante'), ('editar_denunciante', 'Puede actualizar denunciante'), ('eliminar_denunciante', 'Puede eliminar denunciante')],
            },
        ),
        migrations.CreateModel(
            name='RegistroFilmico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=6, verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_by', models.CharField(max_length=6, verbose_name='Actualizado por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_by', models.CharField(blank=True, max_length=6, null=True, verbose_name='Eliminado por')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('estatus', models.CharField(choices=[('reg', 'Registrado'), ('pro', 'En Proceso'), ('nop', 'No Procede')], max_length=3)),
                ('camara', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(50), helpers.validForm.TextValidator()], verbose_name='Cámara')),
                ('motivo_solicitud', models.TextField(max_length=400, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(400), helpers.validForm.TextValidator()], verbose_name='Motivo de Solicitud')),
                ('ente_solicita', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(50), helpers.validForm.TextValidator()], verbose_name='Ente que Solicita')),
                ('direccion', models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(150), helpers.validForm.TextValidator()], verbose_name='Dirección')),
                ('fecha_solicitud', models.DateField(blank=True, null=True)),
                ('fecha_culminacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Registro Filmico',
                'verbose_name_plural': 'Registros Filmicos',
                'permissions': [('listar_registro_filmico', 'Puede listar registros filmicos'), ('agregar_registro_filmico', 'Puede agregar registro filmico'), ('ver_registro_filmico', 'Puede ver registro filmico'), ('editar_registro_filmico', 'Puede actualizar registro filmico'), ('eliminar_registro_filmico', 'Puede eliminar registro filmico'), ('exel_registro_filmico', 'Puede exportar a exel registro filmico')],
            },
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=6, verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_by', models.CharField(max_length=6, verbose_name='Actualizado por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('deleted_by', models.CharField(blank=True, max_length=6, null=True, verbose_name='Eliminado por')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('estatus', models.CharField(choices=[('reg', 'Registrado'), ('pro', 'En Proceso'), ('nop', 'No Procede')], max_length=3)),
                ('ente', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(50), helpers.validForm.TextValidator()], verbose_name='Ente Relacionado')),
                ('motivo', models.TextField(max_length=400, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(400), helpers.validForm.TextValidator()])),
                ('zona', models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(150), helpers.validForm.TextValidator()], verbose_name='Zona del Incidente')),
                ('fecha_denuncia', models.DateField(verbose_name='Fecha de la denuncia')),
                ('fecha_incidente', models.DateField(blank=True, null=True, verbose_name='Fecha del incidente')),
                ('denunciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asesoria.denunciado')),
                ('denunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asesoria.denunciante')),
            ],
            options={
                'verbose_name': 'Denuncia',
                'verbose_name_plural': 'Denuncias',
                'permissions': [('listar_denuncia', 'Puede listar denuncias'), ('agregar_denuncia', 'Puede agregar denuncia'), ('ver_denuncia', 'Puede ver denuncia'), ('editar_denuncia', 'Puede actualizar denuncia'), ('eliminar_denuncia', 'Puede eliminar denuncia'), ('exel_denuncia', 'Puede exportar a exel denuncias')],
            },
        ),
    ]
