# Generated by Django 5.1.1 on 2025-03-22 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asesoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='denuncia',
            options={'permissions': [('listar_denuncia', 'Puede listar denuncias'), ('agregar_denuncia', 'Puede agregar denuncia'), ('ver_denuncia', 'Puede ver denuncia'), ('editar_denuncia', 'Puede actualizar denuncia'), ('eliminar_denuncia', 'Puede eliminar denuncia'), ('exel_denuncia', 'Puede exportar a exel denuncias')], 'verbose_name': 'Denuncia', 'verbose_name_plural': 'Denuncias'},
        ),
        migrations.AlterModelOptions(
            name='denunciado',
            options={'permissions': [('listar_denunciado', 'Puede listar denunciados'), ('agregar_denunciado', 'Puede agregar denunciado'), ('ver_denunciado', 'Puede ver denunciado'), ('editar_denunciado', 'Puede actualizar denunciado'), ('eliminar_denunciado', 'Puede eliminar denunciado')], 'verbose_name': 'Denunciado', 'verbose_name_plural': 'Denunciados'},
        ),
        migrations.AlterModelOptions(
            name='denunciante',
            options={'permissions': [('listar_denunciante', 'Puede listar denunciantes'), ('agregar_denunciante', 'Puede agregar denunciante'), ('ver_denunciante', 'Puede ver denunciante'), ('editar_denunciante', 'Puede actualizar denunciante'), ('eliminar_denunciante', 'Puede eliminar denunciante')], 'verbose_name': 'Denunciante', 'verbose_name_plural': 'Denunciantes'},
        ),
        migrations.AlterModelOptions(
            name='registrofilmico',
            options={'permissions': [('listar_registroFilmico', 'Puede listar registros filmicos'), ('agregar_registroFilmico', 'Puede agregar registro filmico'), ('ver_registroFilmico', 'Puede ver registro filmico'), ('editar_registroFilmico', 'Puede actualizar registro filmico'), ('eliminar_registroFilmico', 'Puede eliminar registro filmico'), ('exel_registroFilmico', 'Puede exportar a exel registro filmico')], 'verbose_name': 'registro_filmico', 'verbose_name_plural': 'registro_filmicos'},
        ),
    ]
