# Generated by Django 5.1.1 on 2025-04-07 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asesoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrofilmico',
            options={'permissions': [('listar_registro_filmico', 'Puede listar registros filmicos'), ('agregar_registro_filmico', 'Puede agregar registro filmico'), ('ver_registro_filmico', 'Puede ver registro filmico'), ('editar_registro_filmico', 'Puede actualizar registro filmico'), ('eliminar_registro_filmico', 'Puede eliminar registro filmico'), ('exel_registro_filmico', 'Puede exportar a exel registro filmico')], 'verbose_name': 'Registro Filmico', 'verbose_name_plural': 'Registros Filmicos'},
        ),
    ]
