# Generated by Django 5.1.1 on 2025-04-06 20:19

import django.core.validators
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='ente',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(50), helpers.validForm.TextValidator()], verbose_name='Ente Relacionado'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='zona',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(150), helpers.validForm.TextValidator()], verbose_name='Zona del Incidente'),
        ),
        migrations.AlterField(
            model_name='denunciante',
            name='cedula',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(14), helpers.validForm.CedulaVenezolanaValidator()], verbose_name='Cédula del denunciante'),
        ),
        migrations.AlterField(
            model_name='registrofilmico',
            name='camara',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(50), helpers.validForm.TextValidator()], verbose_name='Cámara'),
        ),
        migrations.AlterField(
            model_name='registrofilmico',
            name='ente_solicita',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(50), helpers.validForm.TextValidator()], verbose_name='Ente que Solicita'),
        ),
        migrations.AlterField(
            model_name='registrofilmico',
            name='motivo_solicitud',
            field=models.TextField(max_length=400, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(400), helpers.validForm.TextValidator()], verbose_name='Motivo de Solicitud'),
        ),
    ]
