# Generated by Django 5.1.1 on 2025-04-06 23:22

import django.core.validators
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesoria', '0002_alter_denuncia_ente_alter_denuncia_zona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrofilmico',
            name='direccion',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(150), helpers.validForm.TextValidator()], verbose_name='Dirección'),
        ),
    ]
