# Generated by Django 5.1.1 on 2025-03-29 18:44

import django.core.validators
import helpers.validForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesoria', '0002_alter_denuncia_options_alter_denunciado_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='ente',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(50), helpers.validForm.TextValidator()]),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='motivo',
            field=models.TextField(max_length=400, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(400), helpers.validForm.TextValidator()]),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='zona',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(150), helpers.validForm.TextValidator()], verbose_name='Zona del incidente'),
        ),
        migrations.AlterField(
            model_name='denunciado',
            name='apellidos',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(120), helpers.validForm.TextValidator()], verbose_name='Apellido del denunciado'),
        ),
        migrations.AlterField(
            model_name='denunciado',
            name='direccion',
            field=models.CharField(blank=True, max_length=180, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(180), helpers.validForm.TextValidator()], verbose_name='Dirección del denunciado'),
        ),
        migrations.AlterField(
            model_name='denunciado',
            name='nombres',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(120), helpers.validForm.TextValidator()], verbose_name='Nombre del denunciado'),
        ),
        migrations.AlterField(
            model_name='denunciado',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(20), helpers.validForm.PhoneNumberValidator()], verbose_name='Teléfono del denunciado'),
        ),
        migrations.AlterField(
            model_name='denunciante',
            name='apellidos',
            field=models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(120), helpers.validForm.TextValidator()], verbose_name='Apellido del denunciante'),
        ),
        migrations.AlterField(
            model_name='denunciante',
            name='direccion',
            field=models.CharField(max_length=180, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(180), helpers.validForm.TextValidator()], verbose_name='Dirección del denunciante'),
        ),
        migrations.AlterField(
            model_name='denunciante',
            name='nombres',
            field=models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(120), helpers.validForm.TextValidator()], verbose_name='Nombre del denunciante'),
        ),
        migrations.AlterField(
            model_name='denunciante',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(20), helpers.validForm.PhoneNumberValidator()], verbose_name='Teléfono del denunciante'),
        ),
        migrations.AlterField(
            model_name='registrofilmico',
            name='camara',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(50), helpers.validForm.TextValidator()]),
        ),
        migrations.AlterField(
            model_name='registrofilmico',
            name='direccion',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(150), helpers.validForm.TextValidator()], verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='registrofilmico',
            name='ente_solicita',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(50), helpers.validForm.TextValidator()]),
        ),
        migrations.AlterField(
            model_name='registrofilmico',
            name='motivo_solicitud',
            field=models.TextField(max_length=400, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(400), helpers.validForm.TextValidator()]),
        ),
    ]
